// SPDX-License-Identifier: AGPL-3.0-or-later
//
// #1634 — the public projection of a valid capability manifest: the
// release artifact and the checked-in page, byte-identical on every run
// over the same tree. Each record's standing is decided here and
// nowhere else: `gated` for a repository-local reference CI runs at
// every commit, `recorded` for a dated record whose component
// fingerprint still matches, `stale` when the component moved on, and
// `unverified` for a record that did not pass. Only allow-listed fields
// are projected; a record's `private` block never leaves the manifest.
import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

import 'evidence.dart';

/// Twelve hex characters over every file under [paths], path and content
/// in path order: the tested component's version. A change to the
/// component moves it; a change anywhere else does not.
String fingerprint(Iterable<String> paths, Context ctx) {
  final files = <String>[
    for (final p in paths)
      if (Directory('${ctx.root}/$p').existsSync())
        ...Directory('${ctx.root}/$p')
            .listSync(recursive: true)
            .whereType<File>()
            .map((f) => f.path.substring(ctx.root.length + 1))
      else
        p,
  ]..sort();
  final bytes = <int>[
    for (final f in files) ...[
      ...utf8.encode('$f\n'),
      ...File('${ctx.root}/$f').readAsBytesSync(),
    ],
  ];
  return sha256.convert(bytes).toString().substring(0, 12);
}

int _rank(String standing) =>
    const ['unverified', 'stale', 'recorded', 'gated'].indexOf(standing);

/// The public release artifact: deterministic, allow-listed fields only,
/// each record's standing decided here and nowhere else.
Map<String, Object?> project(Map<String, Object?> manifest, Context ctx) {
  final out = <Map<String, Object?>>[];
  for (final raw in manifest['capabilities'] as List) {
    final c = (raw as Map).cast<String, Object?>();
    final component = stringList(c['component']) ?? const [];
    final current = component.isEmpty ? null : fingerprint(component, ctx);
    final records = <Map<String, Object?>>[];
    final best = {for (final s in scopes) s: 'unverified'};
    for (final raw in c['evidence'] as List? ?? const []) {
      final e = (raw as Map).cast<String, Object?>();
      final scope = e['scope'] as String;
      final standing = !isRecorded(scope)
          ? 'gated'
          : e['outcome'] != 'pass'
              ? 'unverified'
              : e['fingerprint'] == current
                  ? 'recorded'
                  : 'stale';
      records.add({
        'scope': scope,
        'ref': e['ref'],
        'standing': standing,
        if (isRecorded(scope)) ...{
          'sha': e['sha'],
          'date': e['date'],
          'outcome': e['outcome'],
        },
      });
      if (_rank(standing) > _rank(best[scope]!)) best[scope] = standing;
    }
    out.add({
      for (final k in ['id', 'outcome', 'status', 'features', 'prerequisites', 'limitations'])
        k: c[k],
      'provider': ?c['provider'],
      'issues': ?c['issues'],
      'fingerprint': ?current,
      'scopes': best,
      'evidence': records,
    });
  }
  return {
    'schema_version': 1,
    'manifest_version': manifest['version'],
    'scopes': scopes,
    'capabilities': out,
  };
}

String renderRelease(Map<String, Object?> projection) =>
    '${const JsonEncoder.withIndent('  ').convert(projection)}\n';

String _cell(Map<String, Object?> cap, String scope) {
  final standing = (cap['scopes'] as Map)[scope] as String;
  if (standing != 'recorded') return standing == 'unverified' ? '—' : standing;
  final dates = (cap['evidence'] as List)
      .cast<Map<String, Object?>>()
      .where((e) => e['scope'] == scope && e['standing'] == 'recorded')
      .map((e) => e['date']);
  return 'recorded ${dates.join(', ')}';
}

String _link(String ref) => ref.startsWith('ci:')
    ? '`${ref.substring(3)}` row of the [quality report](../../.github/quality-manifest.psv)'
    : '[`$ref`](../../$ref)';

/// The checked-in page: one table, then one section per capability.
String renderPage(Map<String, Object?> projection) {
  final b = StringBuffer()
    ..writeln('<!-- GENERATED by `dart run tool/capability_evidence.dart` from '
        '`$manifestPath` — do not edit by hand. -->')
    ..writeln()
    ..writeln('# Capabilities and their evidence')
    ..writeln()
    ..writeln('Manifest `${projection['manifest_version']}`. Four things are '
        'kept apart: whether the code is **shipped** or still **roadmap**; '
        'whether a test **gated** at every commit covers it; whether a '
        'dated record was **recorded** against the component as it is '
        'now; and whether that record has gone **stale** because the '
        'component moved on. A dash is `unverified`. A local stub or a '
        'replayed database is a local integration, never a provider '
        'sandbox, and one provider\'s record says nothing about another '
        '(#1634).')
    ..writeln()
    ..writeln('| Capability | Code | ${scopes.map((s) => '`$s`').join(' | ')} |')
    ..writeln('|---|---|${'---|' * scopes.length}');
  final caps = (projection['capabilities'] as List).cast<Map<String, Object?>>();
  for (final c in caps) {
    b.writeln('| [${c['id']}](#${(c['id'] as String).replaceAll('.', '')}) | '
        '${c['status']} | ${scopes.map((s) => _cell(c, s)).join(' | ')} |');
  }
  for (final c in caps) {
    final features = (c['features'] as List).cast<String>();
    b
      ..writeln()
      ..writeln('## ${c['id']}')
      ..writeln()
      ..writeln(c['outcome'])
      ..writeln()
      ..writeln('- **Code:** ${c['status']}'
          '${c['fingerprint'] != null ? ' · component `${c['fingerprint']}`' : ''}'
          '${c['provider'] != null ? ' · provider `${c['provider']}`' : ''}')
      ..writeln('- **Needs:** ${c['prerequisites']}')
      ..writeln('- **Limits:** ${c['limitations']}');
    if (features.isNotEmpty) {
      b.writeln('- **Feature flags:** ${features.map((f) => '`$f`').join(', ')}');
    }
    if (c['issues'] != null) {
      b.writeln('- **Delivered by:** ${(c['issues'] as List).map((i) => '#$i').join(', ')}');
    }
    for (final e in (c['evidence'] as List).cast<Map<String, Object?>>()) {
      b.writeln('- `${e['scope']}` · **${e['standing']}** · ${_link(e['ref'] as String)}'
          '${e['sha'] != null ? ' · sha `${e['sha']}` · ${e['date']} · ${e['outcome']}' : ''}');
    }
  }
  return b.toString();
}
