// SPDX-License-Identifier: AGPL-3.0-or-later
// GENERATED by `dart run tool/build_mcp_contract.dart` from contracts/mcp/operations.json (#1609). Do not edit.

export const MCP_CONTRACT_VERSION = 1;
export const MCP_TOOL_PREFIX = "deskilo_";
export type McpStatus =
  | "completed"
  | "pending_validation"
  | "requires_confirmation"
  | "denied"
  | "conflict"
  | "validation_error"
  | "not_found"
  | "rate_limited";
export type McpOperationId =
  | "list_workspaces"
  | "get_capabilities"
  | "get_availability"
  | "list_my_reservations"
  | "get_my_statement"
  | "list_my_invoices"
  | "create_reservation"
  | "update_reservation"
  | "check_in"
  | "check_out"
  | "request_reservation_deletion"
  | "request_invoice_issue"
  | "request_invoice_void"
  | "request_refund"
  | "request_member_status_change"
  | "request_subscription_change"
  | "list_pending_validations"
  | "get_validation"
  | "respond_to_validation";

export interface McpEnvelope<T = Record<string, unknown>> {
  schema_version: 1;
  request_id: string;
  operation: McpOperationId;
  workspace_id?: string;
  status: McpStatus;
  data?: T;
  event_id?: string;
  error?: { code: string; fields?: Record<string, string> };
}

export interface McpOperation {
  id: McpOperationId;
  rpc: string | null;
  handler: boolean;
  dispatch: boolean;
  authority: { kind: "self" | "member" | "permission"; permission?: string };
  features: string[];
  scope: "discovery" | "own" | "workspace";
  mutation: "read" | "write" | "request" | "decision";
  idempotency: "none" | "request_id";
  confirmation: "none" | "native";
  params: Record<string, string>;
  fixed: Record<string, unknown>;
  output: string[];
}

export const MCP_OPERATIONS: Record<McpOperationId, McpOperation> = {
  list_workspaces: {"id":"list_workspaces","rpc":null,"handler":false,"dispatch":false,"authority":{"kind":"self"},"features":[],"scope":"discovery","mutation":"read","idempotency":"none","confirmation":"none","params":{},"fixed":{},"output":["workspace_id","name","role","environment"]},
  get_capabilities: {"id":"get_capabilities","rpc":null,"handler":false,"dispatch":true,"authority":{"kind":"member"},"features":["mcpAccess"],"scope":"workspace","mutation":"read","idempotency":"none","confirmation":"none","params":{},"fixed":{},"output":["operations","unavailable"]},
  get_availability: {"id":"get_availability","rpc":null,"handler":false,"dispatch":false,"authority":{"kind":"member"},"features":["mcpAccess"],"scope":"workspace","mutation":"read","idempotency":"none","confirmation":"none","params":{},"fixed":{},"output":["places","window"]},
  list_my_reservations: {"id":"list_my_reservations","rpc":null,"handler":false,"dispatch":false,"authority":{"kind":"self"},"features":["mcpAccess"],"scope":"own","mutation":"read","idempotency":"none","confirmation":"none","params":{},"fixed":{},"output":["reservation_id","place","starts_at","ends_at","status"]},
  get_my_statement: {"id":"get_my_statement","rpc":"member_statement","handler":false,"dispatch":true,"authority":{"kind":"self"},"features":["mcpAccess","moneyTab"],"scope":"own","mutation":"read","idempotency":"none","confirmation":"none","params":{"member_id":"p_member_id","period":"p_period"},"fixed":{},"output":["lines","total_cents","currency"]},
  list_my_invoices: {"id":"list_my_invoices","rpc":null,"handler":false,"dispatch":false,"authority":{"kind":"self"},"features":["mcpAccess","invoicing"],"scope":"own","mutation":"read","idempotency":"none","confirmation":"none","params":{},"fixed":{},"output":["invoice_id","number","period","total_cents","status"]},
  create_reservation: {"id":"create_reservation","rpc":"create_reservation_once","handler":false,"dispatch":true,"authority":{"kind":"self"},"features":["mcpAccess"],"scope":"own","mutation":"write","idempotency":"request_id","confirmation":"none","params":{"request_id":"p_client_request_id","workspace_id":"p_workspace_id","seat_id":"p_seat_id","desk_id":"p_desk_id","office_id":"p_office_id","level_id":"p_level_id","starts_at":"p_starts_at","ends_at":"p_ends_at"},"fixed":{"p_check_in":false},"output":["reservation_id"]},
  update_reservation: {"id":"update_reservation","rpc":"update_reservation","handler":false,"dispatch":true,"authority":{"kind":"self"},"features":["mcpAccess"],"scope":"own","mutation":"write","idempotency":"request_id","confirmation":"none","params":{"reservation_id":"p_reservation_id","starts_at":"p_starts_at","ends_at":"p_ends_at"},"fixed":{},"output":[]},
  check_in: {"id":"check_in","rpc":"check_in_reservation","handler":false,"dispatch":true,"authority":{"kind":"self"},"features":["mcpAccess"],"scope":"own","mutation":"write","idempotency":"request_id","confirmation":"none","params":{"reservation_id":"p_reservation_id"},"fixed":{},"output":[]},
  check_out: {"id":"check_out","rpc":"check_out_reservation","handler":false,"dispatch":true,"authority":{"kind":"self"},"features":["mcpAccess"],"scope":"own","mutation":"write","idempotency":"request_id","confirmation":"none","params":{"reservation_id":"p_reservation_id"},"fixed":{},"output":[]},
  request_reservation_deletion: {"id":"request_reservation_deletion","rpc":"request_reservation_deletion","handler":false,"dispatch":true,"authority":{"kind":"self"},"features":["mcpAccess"],"scope":"own","mutation":"request","idempotency":"request_id","confirmation":"none","params":{"reservation_id":"p_reservation_id","reason":"p_reason"},"fixed":{},"output":["event_id"]},
  request_invoice_issue: {"id":"request_invoice_issue","rpc":"request_invoice_issue","handler":false,"dispatch":true,"authority":{"kind":"permission","permission":"issueInvoices"},"features":["mcpAccess","invoicing"],"scope":"workspace","mutation":"request","idempotency":"request_id","confirmation":"native","params":{"workspace_id":"p_workspace_id","member_id":"p_member_id","period":"p_period","kind":"p_kind"},"fixed":{},"output":["event_id","invoice_id"]},
  request_invoice_void: {"id":"request_invoice_void","rpc":"request_invoice_void","handler":false,"dispatch":true,"authority":{"kind":"permission","permission":"issueInvoices"},"features":["mcpAccess","invoicing"],"scope":"workspace","mutation":"request","idempotency":"request_id","confirmation":"native","params":{"invoice_id":"p_invoice_id","reason":"p_reason"},"fixed":{},"output":["event_id"]},
  request_refund: {"id":"request_refund","rpc":"request_refund","handler":false,"dispatch":true,"authority":{"kind":"permission","permission":"issueInvoices"},"features":["mcpAccess","invoicing"],"scope":"workspace","mutation":"request","idempotency":"request_id","confirmation":"native","params":{"invoice_id":"p_invoice_id","note":"p_note"},"fixed":{},"output":["event_id"]},
  request_member_status_change: {"id":"request_member_status_change","rpc":"request_member_status_change","handler":false,"dispatch":true,"authority":{"kind":"permission","permission":"manageMembers"},"features":["mcpAccess"],"scope":"workspace","mutation":"request","idempotency":"request_id","confirmation":"native","params":{"member_id":"p_member_id","status":"p_status"},"fixed":{},"output":["event_id"]},
  request_subscription_change: {"id":"request_subscription_change","rpc":"request_subscription_change","handler":false,"dispatch":true,"authority":{"kind":"permission","permission":"manageBilling"},"features":["mcpAccess"],"scope":"workspace","mutation":"request","idempotency":"request_id","confirmation":"native","params":{"member_id":"p_member_id","pct":"p_pct"},"fixed":{},"output":["event_id"]},
  list_pending_validations: {"id":"list_pending_validations","rpc":null,"handler":false,"dispatch":false,"authority":{"kind":"permission","permission":"manageValidation"},"features":["mcpAccess"],"scope":"workspace","mutation":"read","idempotency":"none","confirmation":"none","params":{},"fixed":{},"output":["event_id","type","requested_at","summary"]},
  get_validation: {"id":"get_validation","rpc":null,"handler":false,"dispatch":false,"authority":{"kind":"permission","permission":"manageValidation"},"features":["mcpAccess"],"scope":"workspace","mutation":"read","idempotency":"none","confirmation":"none","params":{},"fixed":{},"output":["event_id","type","requested_at","summary","decisions"]},
  respond_to_validation: {"id":"respond_to_validation","rpc":"respond_to_event","handler":false,"dispatch":true,"authority":{"kind":"permission","permission":"manageValidation"},"features":["mcpAccess"],"scope":"workspace","mutation":"decision","idempotency":"request_id","confirmation":"native","params":{"event_id":"p_event_id","accept":"p_accept"},"fixed":{},"output":[]},
};

export const MCP_INPUT_SCHEMAS: Record<McpOperationId, unknown> = {
  list_workspaces: {"type":"object","additionalProperties":false,"properties":{"limit":{"type":"integer","minimum":1,"maximum":100}},"required":[]},
  get_capabilities: {"type":"object","additionalProperties":false,"properties":{"workspace_id":{"type":"string","format":"uuid"}},"required":["workspace_id"]},
  get_availability: {"type":"object","additionalProperties":false,"properties":{"workspace_id":{"type":"string","format":"uuid"},"starts_at":{"type":"string","format":"date-time","pattern":"(Z|[+-]\\d{2}:\\d{2})$"},"ends_at":{"type":"string","format":"date-time","pattern":"(Z|[+-]\\d{2}:\\d{2})$"}},"required":["workspace_id","starts_at","ends_at"]},
  list_my_reservations: {"type":"object","additionalProperties":false,"properties":{"workspace_id":{"type":"string","format":"uuid"},"from":{"type":"string","format":"date-time","pattern":"(Z|[+-]\\d{2}:\\d{2})$"},"to":{"type":"string","format":"date-time","pattern":"(Z|[+-]\\d{2}:\\d{2})$"},"limit":{"type":"integer","minimum":1,"maximum":100}},"required":["workspace_id","from","to"]},
  get_my_statement: {"type":"object","additionalProperties":false,"properties":{"workspace_id":{"type":"string","format":"uuid"},"member_id":{"type":"string","format":"uuid"},"period":{"type":"string","pattern":"^\\d{4}-(0[1-9]|1[0-2])$"}},"required":["workspace_id","member_id","period"]},
  list_my_invoices: {"type":"object","additionalProperties":false,"properties":{"workspace_id":{"type":"string","format":"uuid"},"limit":{"type":"integer","minimum":1,"maximum":100}},"required":["workspace_id"]},
  create_reservation: {"type":"object","additionalProperties":false,"properties":{"request_id":{"type":"string","format":"uuid"},"workspace_id":{"type":"string","format":"uuid"},"seat_id":{"type":"string","format":"uuid"},"desk_id":{"type":"string","format":"uuid"},"office_id":{"type":"string","format":"uuid"},"level_id":{"type":"string","format":"uuid"},"starts_at":{"type":"string","format":"date-time","pattern":"(Z|[+-]\\d{2}:\\d{2})$"},"ends_at":{"type":"string","format":"date-time","pattern":"(Z|[+-]\\d{2}:\\d{2})$"}},"required":["request_id","workspace_id","starts_at","ends_at"]},
  update_reservation: {"type":"object","additionalProperties":false,"properties":{"request_id":{"type":"string","format":"uuid"},"workspace_id":{"type":"string","format":"uuid"},"reservation_id":{"type":"string","format":"uuid"},"starts_at":{"type":"string","format":"date-time","pattern":"(Z|[+-]\\d{2}:\\d{2})$"},"ends_at":{"type":"string","format":"date-time","pattern":"(Z|[+-]\\d{2}:\\d{2})$"}},"required":["request_id","workspace_id","reservation_id","starts_at","ends_at"]},
  check_in: {"type":"object","additionalProperties":false,"properties":{"request_id":{"type":"string","format":"uuid"},"workspace_id":{"type":"string","format":"uuid"},"reservation_id":{"type":"string","format":"uuid"}},"required":["request_id","workspace_id","reservation_id"]},
  check_out: {"type":"object","additionalProperties":false,"properties":{"request_id":{"type":"string","format":"uuid"},"workspace_id":{"type":"string","format":"uuid"},"reservation_id":{"type":"string","format":"uuid"}},"required":["request_id","workspace_id","reservation_id"]},
  request_reservation_deletion: {"type":"object","additionalProperties":false,"properties":{"request_id":{"type":"string","format":"uuid"},"workspace_id":{"type":"string","format":"uuid"},"reservation_id":{"type":"string","format":"uuid"},"reason":{"type":"string","maxLength":500}},"required":["request_id","workspace_id","reservation_id"]},
  request_invoice_issue: {"type":"object","additionalProperties":false,"properties":{"request_id":{"type":"string","format":"uuid"},"workspace_id":{"type":"string","format":"uuid"},"member_id":{"type":"string","format":"uuid"},"period":{"type":"string","pattern":"^\\d{4}-(0[1-9]|1[0-2])$"},"kind":{"type":"string","enum":["full","subscription","usage"]}},"required":["request_id","workspace_id","member_id","period"]},
  request_invoice_void: {"type":"object","additionalProperties":false,"properties":{"request_id":{"type":"string","format":"uuid"},"workspace_id":{"type":"string","format":"uuid"},"invoice_id":{"type":"string","format":"uuid"},"reason":{"type":"string","maxLength":500}},"required":["request_id","workspace_id","invoice_id"]},
  request_refund: {"type":"object","additionalProperties":false,"properties":{"request_id":{"type":"string","format":"uuid"},"workspace_id":{"type":"string","format":"uuid"},"invoice_id":{"type":"string","format":"uuid"},"note":{"type":"string","maxLength":500}},"required":["request_id","workspace_id","invoice_id"]},
  request_member_status_change: {"type":"object","additionalProperties":false,"properties":{"request_id":{"type":"string","format":"uuid"},"workspace_id":{"type":"string","format":"uuid"},"member_id":{"type":"string","format":"uuid"},"status":{"type":"string","enum":["active","paused","exited"]}},"required":["request_id","workspace_id","member_id","status"]},
  request_subscription_change: {"type":"object","additionalProperties":false,"properties":{"request_id":{"type":"string","format":"uuid"},"workspace_id":{"type":"string","format":"uuid"},"member_id":{"type":"string","format":"uuid"},"pct":{"type":"integer","minimum":0,"maximum":100}},"required":["request_id","workspace_id","member_id","pct"]},
  list_pending_validations: {"type":"object","additionalProperties":false,"properties":{"workspace_id":{"type":"string","format":"uuid"},"limit":{"type":"integer","minimum":1,"maximum":100}},"required":["workspace_id"]},
  get_validation: {"type":"object","additionalProperties":false,"properties":{"workspace_id":{"type":"string","format":"uuid"},"event_id":{"type":"string","format":"uuid"}},"required":["workspace_id","event_id"]},
  respond_to_validation: {"type":"object","additionalProperties":false,"properties":{"request_id":{"type":"string","format":"uuid"},"workspace_id":{"type":"string","format":"uuid"},"event_id":{"type":"string","format":"uuid"},"accept":{"type":"boolean"}},"required":["request_id","workspace_id","event_id","accept"]},
};

export const MCP_FORBIDDEN_INPUTS: readonly string[] = ["actor","actor_id","user_id","role","roles","permission","permissions","is_admin","is_owner","sql","query","table","rpc","function","url","approval","approved","decided_by","status_override"];
