// SPDX-License-Identifier: AGPL-3.0-or-later
//
// #1455 — digests of the migrations that were applied to the reference
// project, and the two things a baseline lets a lint say: a recorded file
// was edited, or a file was inserted below the baseline.
import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

const String migrationsDir = 'supabase/migrations';
const String baselinePath = 'supabase/APPLIED.sha256';

String digestOf(File file) => sha256.convert(file.readAsBytesSync()).toString();

/// `NNNN` from `NNNN_name.sql`.
String numberOf(String fileName) => fileName.split('_').first;

/// The baseline text: a header, then `sha256  NNNN_name.sql` per applied
/// file, in file order, up to [through] inclusive when given.
String recordApplied(Directory dir, {String? through}) {
  final files = dir
      .listSync()
      .whereType<File>()
      .where((f) => RegExp(r'^\d{4}_.*\.sql$').hasMatch(f.uri.pathSegments.last))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));
  final lines = <String>[
    '# GENERATED by `dart run tool/record_applied_migrations.dart` (#1455).',
    '# Every migration listed here has been APPLIED to the reference project',
    '# and is history: its file may not change, and no file may be inserted',
    '# below the highest number listed. A file that is not listed is a',
    '# draft and stays free. Record a migration here in the same PR that',
    '# applies it.',
    for (final f in files)
      if (through == null || numberOf(f.uri.pathSegments.last).compareTo(through) <= 0)
        '${digestOf(f)}  ${f.uri.pathSegments.last}',
  ];
  return '${lines.join('\n')}\n';
}

/// `name → digest` from the baseline text.
Map<String, String> parseBaseline(String text) => {
      for (final line in const LineSplitter().convert(text))
        if (line.isNotEmpty && !line.startsWith('#'))
          line.substring(line.indexOf('  ') + 2).trim(): line.substring(0, line.indexOf('  ')),
    };

/// What is wrong, as sentences; empty when the tree honours the baseline.
List<String> auditBaseline(Directory dir, Map<String, String> baseline) {
  final problems = <String>[];
  if (baseline.isEmpty) return problems;
  final highest = baseline.keys.map(numberOf).reduce((a, b) => a.compareTo(b) >= 0 ? a : b);
  final present = {
    for (final f in dir.listSync().whereType<File>())
      if (RegExp(r'^\d{4}_.*\.sql$').hasMatch(f.uri.pathSegments.last))
        f.uri.pathSegments.last: f,
  };
  for (final entry in baseline.entries) {
    final file = present[entry.key];
    if (file == null) {
      problems.add('${entry.key} was applied and is recorded, but the file is gone — '
          'an applied migration is never removed or renamed');
    } else if (digestOf(file) != entry.value) {
      problems.add('${entry.key} was applied and is recorded, but its file changed — '
          'an applied migration is never edited; write a forward migration');
    }
  }
  for (final name in present.keys) {
    if (!baseline.containsKey(name) && numberOf(name).compareTo(highest) <= 0) {
      problems.add('$name sits below the applied baseline ($highest) and is not '
          'recorded — a new migration takes the next free number above it');
    }
  }
  return problems..sort();
}
