// SPDX-License-Identifier: 0BSD
import 'dart:convert';
import 'dart:io';
import 'package:deskilo/features/workspace/domain/workspace_process.dart';

String buildProcessLabels() {
  final en = jsonDecode(File('lib/l10n/_fragments/processes_en.arb').readAsStringSync()) as Map<String, dynamic>;
  final entries = <String, String>{
    for (final p in workspaceProcesses) p.key: p.titleKey,
    for (final p in workspaceProcesses)
      for (final s in p.subprocesses) s.key: s.titleKey,
  };
  String quote(String value) => "'${value.replaceAll("'", r"\'")}'";
  return '''// SPDX-License-Identifier: 0BSD
// GENERATED by tool/build_process_labels.dart. Do not edit.
import '../../../l10n/app_localizations.dart';

({String title, String description}) processCopy(AppLocalizations? l10n, String key) =>
    switch (key) {
${entries.entries.map((e) => "  '${e.key}' => (title: l10n?.${e.value} ?? ${quote(en[e.value] as String)},\n    description: l10n?.${e.value}Desc ?? ${quote(en['${e.value}Desc'] as String)}),").join('\n')}
  _ => throw ArgumentError.value(key, 'key', 'Unknown process label'),
};

String processLabel(AppLocalizations? l10n, String key) => processCopy(l10n, key).title;
''';
}

void main() => File('lib/features/workspace/presentation/process_names.dart')
    .writeAsStringSync(buildProcessLabels());
