// SPDX-License-Identifier: 0BSD
// Generates the business catalogue without importing Flutter.
import 'dart:convert';
import 'dart:io';
import 'package:deskilo/features/workspace/domain/workspace_feature.dart';
import 'package:deskilo/features/workspace/domain/workspace_process.dart';

String buildProcessCatalogue() {
  final messages = jsonDecode(File('lib/l10n/app_en.arb').readAsStringSync())
      as Map<String, dynamic>;
  final out = StringBuffer('''# Workspace process catalogue

Generated by `dart run tool/build_process_catalogue.dart` (#1325).
Membership is business grouping; dependencies and defaults come only from
`featureManifest`. Permissions remain separate and server-enforced.
Shared prerequisites have one home. A server-only workflow remains selectable;
unsupported flags are internal until an implemented workflow consumes them.
Subscriptions, prepaid products and basic floor-plan editing do not have their
own flags: this catalogue does not invent switches for those workflows.

| Process | Subprocess | Feature | User outcome | Tier | Surface | Requires | Default | Classification |
|---|---|---|---|---|---|---|---|---|
''');
  void row(String process, String subprocess, WorkspaceFeature feature,
      String classification) {
    final m = featureManifest[feature]!;
    final key = 'feature${feature.name[0].toUpperCase()}${feature.name.substring(1)}';
    final outcome = messages['${key}Desc'] ?? messages[key] ??
        messages['${key}Title'] ?? feature.name;
    final text = outcome.toString().replaceAll('|', '/').replaceAll('\n', ' ');
    out.writeln('| $process | $subprocess | ${feature.name} | $text | '
        '${m.tier.name} | ${m.surface.name} | ${m.requires?.name ?? "—"} | '
        '${m.defaultOn} | $classification |');
  }
  for (final process in workspaceProcesses) {
    for (final subprocess in process.subprocesses) {
      for (final feature in subprocess.capabilities) {
        row(process.key, subprocess.key, feature, 'selectable');
      }
    }
  }
  for (final entry in internalCapabilities.entries) {
    row('internal', '—', entry.key, entry.value);
  }
  return out.toString();
}

void main() => File('docs/design/process-catalogue.md')
    .writeAsStringSync(buildProcessCatalogue());
