// SPDX-License-Identifier: AGPL-3.0-or-later
//
// #1282 — expands each builtin template's `feature_profile` into its full
// `configuration.workspace.feature_flags`.
//
// #1599 — the same expansion for the owner-private variants under
// `supabase/templates/variants/`, plus the review each one is read
// through: a table that says, row by row, whether a value is something
// the field report DEMANDED or something the variant INHERITED.
//
//   dart run tool/build_builtin_templates.dart          # rewrite the files
//   dart run tool/build_builtin_templates.dart --check  # exit 1 on drift
import 'dart:convert';
import 'dart:io';

import 'package:deskilo/features/workspace/domain/template_feature_profile.dart';

const _builtinDir = 'supabase/templates';
const _variantDir = 'supabase/templates/variants';

List<File> _jsonFiles(String dir) => Directory(dir)
    .listSync()
    .whereType<File>()
    .where((f) => f.path.endsWith('.json'))
    .toList()
  ..sort((a, b) => a.path.compareTo(b.path));

/// What each `provenance.rows[].source` means in the review. The order is
/// the order the sections are printed in: what was asked for first, then
/// what was corrected, then what is still missing, then what was merely
/// inherited.
const _sections = <String, String>{
  'explicit': 'Demanded by the report',
  'correction': 'Corrected, and not silently',
  'unresolved': 'Unresolved — do not invent',
  'inherited': 'Inherited or default',
};

/// The review `pezenas_coworking.md` is: the payload, read back as a
/// table that says which values the field report DEMANDED.
String templateReview(Map<String, dynamic> template) {
  final provenance =
      Map<String, dynamic>.from(template['provenance'] as Map? ?? const {});
  final rows = [
    for (final r in provenance['rows'] as List? ?? const [])
      Map<String, dynamic>.from(r as Map),
  ];
  final acceptance =
      Map<String, dynamic>.from(template['acceptance'] as Map? ?? const {});
  final months =
      Map<String, dynamic>.from(acceptance['half_days'] as Map? ?? const {});
  final b = StringBuffer()
    ..writeln('<!-- Generated by `dart run tool/build_builtin_templates.dart`'
        ' from ${template['key']}.json. Do not edit. -->')
    ..writeln()
    ..writeln('# ${template['name']} — configuration review')
    ..writeln()
    ..writeln('`${template['key']}` · visibility `${template['visibility']}` ·'
        ' template format ${template['schema_version']}')
    ..writeln()
    ..writeln('Source: ${provenance['source_document']}')
    ..writeln()
    ..writeln('A reviewer reads this to answer one question: which of these'
        ' values did the report actually ask for? Everything under'
        ' *${_sections['inherited']}* is a choice nobody at Pézenas made.');
  for (final entry in _sections.entries) {
    final here = rows.where((r) => r['source'] == entry.key).toList();
    if (here.isEmpty) continue;
    b
      ..writeln()
      ..writeln('## ${entry.value}')
      ..writeln()
      ..writeln('| Area | Value | Where | Note |')
      ..writeln('|---|---|---|---|');
    for (final r in here) {
      b.writeln('| ${r['area']} | ${r['value']} | ${r['where']} |'
          ' ${r['note'] ?? '—'} |');
    }
  }
  if (months.isNotEmpty) {
    b
      ..writeln()
      ..writeln('## Included half-days, month by month')
      ..writeln()
      ..writeln('`${acceptance['formula']}`')
      ..writeln()
      ..writeln('| Month | 50 % | 100 % |')
      ..writeln('|---|---:|---:|');
    for (final m in months.keys.toList()..sort()) {
      final pair = months[m] as List;
      b.writeln('| $m | ${pair[0]} | ${pair[1]} |');
    }
  }
  return b.toString();
}

void main(List<String> args) {
  final check = args.contains('--check');
  var drift = false;
  void write(File file, String out) {
    if (out == (file.existsSync() ? file.readAsStringSync() : null)) return;
    drift = true;
    if (check) {
      stderr.writeln('${file.path}: out of date');
    } else {
      file.writeAsStringSync(out);
      stdout.writeln('wrote ${file.path}');
    }
  }

  for (final dir in [_builtinDir, _variantDir]) {
    if (!Directory(dir).existsSync()) continue;
    for (final file in _jsonFiles(dir)) {
      final template =
          Map<String, dynamic>.from(jsonDecode(file.readAsStringSync()) as Map);
      final flags = expandTemplateProfile(template);
      if (flags != null) {
        final config = Map<String, dynamic>.from(
            template['configuration'] as Map? ?? <String, dynamic>{});
        final workspace = Map<String, dynamic>.from(
            config['workspace'] as Map? ?? <String, dynamic>{});
        workspace['feature_flags'] = {
          for (final k in flags.keys.toList()..sort()) k: flags[k],
        };
        config['workspace'] = workspace;
        template['configuration'] = config;
        write(file,
            '${const JsonEncoder.withIndent('  ').convert(template)}\n');
      }
      // A variant carries its own review: the document #1599 asks for,
      // never hand-written beside a payload that has moved on.
      if (dir == _variantDir && template['provenance'] != null) {
        write(File(file.path.replaceFirst(RegExp(r'\.json$'), '.md')),
            templateReview(template));
      }
    }
  }
  if (check && drift) exit(1);
}
