// SPDX-License-Identifier: AGPL-3.0-or-later
//
// #1449 checkpoint 1 — the read/write dependency directions, measured.
//
//   dart run tool/dependency_map.dart
//
// The issue's own numbers came from a snapshot master had already moved
// past, which is what a hand-counted baseline does. This writes them
// from the tree instead, using the SAME scanner `layering_test` ratchets
// on, so the map and the gate cannot drift apart.
//
// #2121 — the map lists facts, not volumes: which features a context's
// presentation still reads a repository from (with the ratchet's number),
// which directed feature pairs exist, which files are over the budget.
// Per-pair import counts, line counts and totals moved with almost every
// pull request and put every other open one in conflict on this file;
// one line per fact, sorted by name, changes only when a fact does, and
// two pull requests that add different facts touch different lines.
import 'dart:io';

import 'layering/analysis.dart';

const String output = 'docs/design/APPLICATION_BOUNDARIES.md';

/// The three contexts #1449 names. Everything else is listed together:
/// naming a context here is a claim that somebody owns it.
const Map<String, List<String>> contexts = {
  'Booking': ['reservations', 'plan', 'calendar', 'editor'],
  'Finance': ['money'],
  'Workspace configuration': ['workspace', 'members', 'profile'],
};

String render(
  Map<String, List<String>> reads,
  Iterable<String> pairs,
  Iterable<String> large,
) {
  final b = StringBuffer()
    ..writeln('<!-- GENERATED by `dart run tool/dependency_map.dart` — '
        'do not edit by hand. -->')
    ..writeln()
    ..writeln('# Application boundaries, as they stand')
    ..writeln()
    ..writeln('Checkpoint 1 of #1449: the read and write directions of '
        'Booking, Finance and Workspace configuration, counted from the '
        'tree rather than remembered. It supersedes the snapshot in the '
        'issue body, which master had already moved past before the '
        'issue was filed.')
    ..writeln()
    ..writeln('A repository read from `presentation/` is **not** a defect '
        'by itself. What #1234 and ADR 0024 ask for is that a *decision* '
        'live in `application/`; a screen that reads a repository to hand '
        'it to a command still counts here, and correctly so — the count '
        'measures how far the extraction has reached, not how wrong the '
        'code is.')
    ..writeln();

  final named = contexts.values.expand((f) => f).toSet();

  b
    ..writeln('## Presentation files still resolving a repository')
    ..writeln()
    ..writeln('| context | feature | files |')
    ..writeln('|---|---|---|');
  for (final entry in contexts.entries) {
    for (final feature in entry.value) {
      final n = reads[feature]?.length ?? 0;
      b.writeln('| ${entry.key} | `$feature` | $n |');
    }
  }
  final others = reads.keys.where((f) => !named.contains(f)).toList()..sort();
  for (final feature in others) {
    b.writeln('| — | `$feature` | ${reads[feature]!.length} |');
  }
  b
    ..writeln()
    ..writeln('`test/lint/layering_test.dart` holds each feature\'s number '
        'as a ceiling that may only fall.')
    ..writeln();

  b
    ..writeln('## Cross-feature imports, by direction')
    ..writeln()
    ..writeln('The direction is the dependency: `a -> b` means files in '
        '`a` import `b`. A pair that appears in both directions is a '
        'cycle between two features, and is called out below. How many '
        'imports a pair carries is not written down: '
        '`dart run tool/dependency_map.dart` prints it.')
    ..writeln();
  final ordered = pairs.toList()..sort();
  for (final pair in ordered) {
    b.writeln('- `$pair`');
  }
  final cycles = reciprocalPairs({for (final p in ordered) p: 1}).toList()
    ..sort();
  b
    ..writeln()
    ..writeln('Reciprocal:')
    ..writeln();
  for (final c in cycles) {
    b.writeln('- `$c`');
  }
  b.writeln();

  b
    ..writeln('## Hand-written files over 600 lines')
    ..writeln()
    ..writeln('The budget line of `test/lint/file_length_test.dart`. A '
        'file here is not necessarily wrong; it is where a decomposition '
        'would pay, and the budgets there say what each one costs today.')
    ..writeln();
  for (final f in large.toList()..sort()) {
    b.writeln('- `$f`');
  }
  b.writeln();

  return b.toString();
}

/// The map of the tree under the working directory, and the volumes it
/// deliberately does not commit.
({String text, String volumes}) mapOfTree() {
  final features = handWrittenDartFiles('lib/features').toList();
  final reads = repositoryReadsByFeature(features);
  final pairs = crossFeatureImports(features);
  final large = [
    for (final f in handWrittenDartFiles('lib'))
      if (f.readAsLinesSync().length > 600) f.path,
  ];
  final total = reads.values.fold<int>(0, (n, l) => n + l.length);
  final volume = pairs.values.fold<int>(0, (n, v) => n + v);
  return (
    text: render(reads, pairs.keys, large),
    volumes: '$total repository reads across ${reads.length} features, '
        '${pairs.length} relationships carrying $volume imports, '
        '${large.length} files over 600 lines',
  );
}

void main() {
  final map = mapOfTree();
  File(output)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(map.text);
  stdout.writeln('wrote $output: ${map.volumes}');
}
