// SPDX-License-Identifier: AGPL-3.0-or-later
//
// #1449 checkpoint 1 — the read/write dependency directions, measured.
//
//   dart run tool/dependency_map.dart
//
// The issue's own numbers came from a snapshot master had already moved
// past, which is what a hand-counted baseline does. This writes them
// from the tree instead, using the SAME scanner `layering_test` ratchets
// on, so the map and the gate cannot drift apart.
import 'dart:io';

import 'layering/analysis.dart';

const String output = 'docs/design/APPLICATION_BOUNDARIES.md';

/// The three contexts #1449 names. Everything else is listed together:
/// naming a context here is a claim that somebody owns it.
const Map<String, List<String>> contexts = {
  'Booking': ['reservations', 'plan', 'calendar', 'editor'],
  'Finance': ['money'],
  'Workspace configuration': ['workspace', 'members', 'profile'],
};

String render(
  Map<String, List<String>> reads,
  Map<String, int> pairs,
  List<({String path, int lines})> large,
) {
  final b = StringBuffer()
    ..writeln('<!-- GENERATED by `dart run tool/dependency_map.dart` — '
        'do not edit by hand. -->')
    ..writeln()
    ..writeln('# Application boundaries, as they stand')
    ..writeln()
    ..writeln('Checkpoint 1 of #1449: the read and write directions of '
        'Booking, Finance and Workspace configuration, counted from the '
        'tree rather than remembered. It supersedes the snapshot in the '
        'issue body, which master had already moved past before the '
        'issue was filed.')
    ..writeln()
    ..writeln('A repository read from `presentation/` is **not** a defect '
        'by itself. What #1234 and ADR 0024 ask for is that a *decision* '
        'live in `application/`; a screen that reads a repository to hand '
        'it to a command still counts here, and correctly so — the count '
        'measures how far the extraction has reached, not how wrong the '
        'code is.')
    ..writeln();

  final named = contexts.values.expand((f) => f).toSet();

  b
    ..writeln('## Presentation files still resolving a repository')
    ..writeln()
    ..writeln('| context | feature | files |')
    ..writeln('|---|---|---|');
  for (final entry in contexts.entries) {
    for (final feature in entry.value) {
      final n = reads[feature]?.length ?? 0;
      b.writeln('| ${entry.key} | `$feature` | $n |');
    }
  }
  final others = reads.keys.where((f) => !named.contains(f)).toList()..sort();
  for (final feature in others) {
    b.writeln('| — | `$feature` | ${reads[feature]!.length} |');
  }
  final total = reads.values.fold<int>(0, (n, l) => n + l.length);
  b
    ..writeln()
    ..writeln('**$total files** across ${reads.length} features. '
        '`test/lint/layering_test.dart` holds each feature\'s number as a '
        'ceiling that may only fall.')
    ..writeln();

  b
    ..writeln('## Cross-feature imports, by direction')
    ..writeln()
    ..writeln('The direction is the dependency: `a -> b` means files in '
        '`a` import `b`. A pair that appears in both directions is a '
        'cycle between two features, and is called out below.')
    ..writeln()
    ..writeln('| pair | imports |')
    ..writeln('|---|---|');
  final ordered = pairs.keys.toList()
    ..sort((a, c) {
      final byCount = pairs[c]!.compareTo(pairs[a]!);
      return byCount != 0 ? byCount : a.compareTo(c);
    });
  for (final pair in ordered) {
    b.writeln('| `$pair` | ${pairs[pair]} |');
  }
  final volume = pairs.values.fold<int>(0, (n, v) => n + v);
  final cycles = reciprocalPairs(pairs).toList()..sort();
  b
    ..writeln()
    ..writeln('**${pairs.length} directed relationships, $volume imports.**')
    ..writeln()
    ..writeln('Reciprocal (${cycles.length}): '
        '${cycles.map((c) => '`$c`').join(', ')}.')
    ..writeln();

  b
    ..writeln('## Hand-written files over 600 lines')
    ..writeln()
    ..writeln('The budget line of `test/lint/file_length_test.dart`. A '
        'file here is not necessarily wrong; it is where a decomposition '
        'would pay, and the budgets say what each one costs today.')
    ..writeln()
    ..writeln('| file | lines |')
    ..writeln('|---|---|');
  for (final f in large) {
    b.writeln('| `${f.path}` | ${f.lines} |');
  }
  b
    ..writeln()
    ..writeln('**${large.length} files.**')
    ..writeln();

  return b.toString();
}

void main() {
  final features = handWrittenDartFiles('lib/features').toList();
  final reads = repositoryReadsByFeature(features);
  final pairs = crossFeatureImports(features);
  final large = [
    for (final f in handWrittenDartFiles('lib'))
      (path: f.path, lines: f.readAsLinesSync().length),
  ].where((f) => f.lines > 600).toList()
    ..sort((a, b) {
      final byLines = b.lines.compareTo(a.lines);
      return byLines != 0 ? byLines : a.path.compareTo(b.path);
    });

  File(output)
    ..parent.createSync(recursive: true)
    ..writeAsStringSync(render(reads, pairs, large));
  stdout.writeln('wrote $output: '
      '${reads.values.fold<int>(0, (n, l) => n + l.length)} repository '
      'reads, ${pairs.length} relationships, ${large.length} large files');
}
