// SPDX-License-Identifier: 0BSD
//
// #1365 — writes the localization audit.
//
//   dart run tool/l10n_audit.dart            # rewrite docs/testing/L10N_AUDIT.md
//   dart run tool/l10n_audit.dart --print    # the table, without writing
import 'dart:io';

import 'l10n_audit/audit.dart';

const output = 'docs/testing/L10N_AUDIT.md';

/// The inventory, as the file's exact text.
String buildAudit() {
  final findings = auditTree(['lib']);
  final byFile = <String, List<Finding>>{};
  for (final f in findings) {
    (byFile[f.path] ??= []).add(f);
  }
  final positions = uiPositions.values.toSet().join(", ");
  final widgets = textWidgets.join("/");
  final out = StringBuffer()
    ..writeln("<!-- GENERATED by `dart run tool/l10n_audit.dart` — "
        "do not edit by hand. -->")
    ..writeln()
    ..writeln("# Localization audit")
    ..writeln()
    ..writeln("Every string in `lib/` that reaches a member's eyes and does "
        "NOT come from `AppLocalizations` (#1365). The repository's idiom is "
        "`l10n?.someKey ?? 'English fallback'`, so a literal is listed only "
        "when nothing hands it a localized value first.")
    ..writeln()
    ..writeln("Positions read: $positions, the text of $widgets, a tooltip's "
        "message, the four snack helpers and a semantics label. Keys, paths, "
        "wire values, formats, trace text and literals made only of "
        "interpolations are not user-facing and are not listed.")
    ..writeln()
    ..writeln("${findings.length} literal(s) in ${byFile.length} file(s) — "
        "each a written decision below. Anything outside them fails "
        "`test/lint/l10n_audit_test.dart`.")
    ..writeln()
    ..writeln("| file | symbol/widget | literal | surface | action |")
    ..writeln("|---|---|---|---|---|");
  for (final path in byFile.keys.toList()..sort()) {
    for (final f in byFile[path]!) {
      final literal = f.literal.replaceAll("|", "/");
      out.writeln("| `${f.path}:${f.line}` | ${f.position} | $literal | "
          "${f.surface} | KEEP_NON_UI_LITERAL |");
    }
  }
  out
    ..writeln()
    ..writeln("## Why each file keeps its literals")
    ..writeln();
  for (final e in classifiedLiterals.entries) {
    out.writeln("- **`${e.key}`** (${e.value.allowed}) — ${e.value.reason}");
  }
  return out.toString();
}

void main(List<String> args) {
  if (args.contains('--print')) {
    stdout.write(buildAudit());
    return;
  }
  File(output).writeAsStringSync(buildAudit());
  stdout.writeln('wrote $output');
}
