// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by `dart run tool/build_public_network_contract.dart` from contracts/public_network/operations.json (#1847). Do not edit.
// ignore_for_file: lines_longer_than_80_chars

import 'public_network_spec.dart';

/// The public network protocol version these specs were generated from.
const int publicNetworkProtocolVersion = 1;

/// Every schema a record or an input is read with.
const Map<String, PublicSchema> publicNetworkSchemas = {
  'DirectorySource': PublicSchema(
    'DirectorySource',
    {
      'origin': PublicField(PublicFieldType.httpsOrigin, required: true),
      'publishable_key': PublicField(PublicFieldType.text, required: true, maxLength: 4096),
    },
  ),
  'PublicContact': PublicSchema(
    'PublicContact',
    {
      'user_id': PublicField(PublicFieldType.uuid),
      'name': PublicField(PublicFieldType.text, required: true, maxLength: 200),
      'owner': PublicField(PublicFieldType.boolean, required: true),
      'available': PublicField(PublicFieldType.boolean, required: true),
    },
  ),
  'PublicWorkspaceDocument': PublicSchema(
    'PublicWorkspaceDocument',
    {
      'name': PublicField(PublicFieldType.text, required: true, maxLength: 200),
      'host_type': PublicField(PublicFieldType.enum_, required: true, values: ['association', 'company', 'person']),
      'currency': PublicField(PublicFieldType.currency),
      'booking_unit': PublicField(PublicFieldType.enum_, values: ['flexible', 'half_day', 'minutes_5', 'minutes_15', 'minutes_30', 'minutes_60', 'full_day', 'hours']),
      'description': PublicField(PublicFieldType.text, maxLength: 4000),
      'address': PublicField(PublicFieldType.text, maxLength: 4000),
      'email': PublicField(PublicFieldType.text, maxLength: 4000),
      'phone': PublicField(PublicFieldType.text, maxLength: 4000),
      'website': PublicField(PublicFieldType.httpsUrl, maxLength: 4000),
      'image_url': PublicField(PublicFieldType.httpsUrl, maxLength: 4000),
      'plan_url': PublicField(PublicFieldType.httpsUrl, maxLength: 4000),
      'plans': PublicField(PublicFieldType.text, maxLength: 4000),
      'latitude': PublicField(PublicFieldType.decimal, min: -90, max: 90),
      'longitude': PublicField(PublicFieldType.decimal, min: -180, max: 180),
      'contacts': PublicField(PublicFieldType.array, schema: 'PublicContact', maxItems: 100),
    },
    mustUnderstand: 'must_understand',
  ),
  'PublicWorkspaceCard': PublicSchema(
    'PublicWorkspaceCard',
    {
      'workspace_id': PublicField(PublicFieldType.uuid, required: true),
      'name': PublicField(PublicFieldType.text, required: true, maxLength: 200),
      'updated_at': PublicField(PublicFieldType.datetime, required: true),
      'document': PublicField(PublicFieldType.object, required: true, schema: 'PublicWorkspaceDocument'),
    },
  ),
  'PublicationInput': PublicSchema(
    'PublicationInput',
    {
      'host_type': PublicField(PublicFieldType.enum_, required: true, values: ['association', 'company', 'person']),
      'description': PublicField(PublicFieldType.text, maxLength: 4000),
      'address': PublicField(PublicFieldType.text, maxLength: 4000),
      'email': PublicField(PublicFieldType.text, maxLength: 4000),
      'phone': PublicField(PublicFieldType.text, maxLength: 4000),
      'website': PublicField(PublicFieldType.text, maxLength: 4000),
      'image_url': PublicField(PublicFieldType.text, maxLength: 4000),
      'plan_url': PublicField(PublicFieldType.text, maxLength: 4000),
      'plans': PublicField(PublicFieldType.text, maxLength: 4000),
      'latitude': PublicField(PublicFieldType.text, maxLength: 4000),
      'longitude': PublicField(PublicFieldType.text, maxLength: 4000),
    },
  ),
  'PublicationDraft': PublicSchema(
    'PublicationDraft',
    {
      'host_type': PublicField(PublicFieldType.text, maxLength: 4000),
      'description': PublicField(PublicFieldType.text, maxLength: 4000),
      'address': PublicField(PublicFieldType.text, maxLength: 4000),
      'email': PublicField(PublicFieldType.text, maxLength: 4000),
      'phone': PublicField(PublicFieldType.text, maxLength: 4000),
      'website': PublicField(PublicFieldType.text, maxLength: 4000),
      'image_url': PublicField(PublicFieldType.text, maxLength: 4000),
      'plan_url': PublicField(PublicFieldType.text, maxLength: 4000),
      'plans': PublicField(PublicFieldType.text, maxLength: 4000),
      'latitude': PublicField(PublicFieldType.text, maxLength: 4000),
      'longitude': PublicField(PublicFieldType.text, maxLength: 4000),
    },
  ),
  'PublicationPage': PublicSchema(
    'PublicationPage',
    {
      'published': PublicField(PublicFieldType.boolean, required: true),
      'document': PublicField(PublicFieldType.object, required: true, schema: 'PublicationDraft'),
    },
  ),
};

/// Every catalogued operation, by a name its callers cannot misspell.
abstract final class PublicNetworkOperations {
  /// List the other installations registered in this installation's public directory.
  static const directorySourcesList = PublicOperationSpec(
    id: 'directory.sources.list',
    surface: PublicSurface.public,
    principal: PublicPrincipal.anonymous,
    authority: PublicAuthority.none,
    mutation: PublicMutation.read,
    features: [],
    relation: 'public_directory_sources',
    select: ['origin', 'publishable_key'],
    order: ['origin.asc'],
    pageSize: 20,
    output: 'DirectorySource',
    cardinality: PublicCardinality.many,
  );

  /// Search the published workspace cards of one installation by name or address.
  static const directoryWorkspacesSearch = PublicOperationSpec(
    id: 'directory.workspaces.search',
    surface: PublicSurface.public,
    principal: PublicPrincipal.anonymous,
    authority: PublicAuthority.none,
    mutation: PublicMutation.read,
    features: ['publicListings'],
    relation: 'public_workspace_cards',
    select: ['workspace_id', 'name', 'document', 'updated_at'],
    order: ['name.asc', 'workspace_id.asc'],
    pageSize: 25,
    timeoutSeconds: 12,
    output: 'PublicWorkspaceCard',
    cardinality: PublicCardinality.many,
  );

  /// Read one published workspace card again, live: no row means it is no longer published.
  static const directoryWorkspacesDetail = PublicOperationSpec(
    id: 'directory.workspaces.detail',
    surface: PublicSurface.public,
    principal: PublicPrincipal.anonymous,
    authority: PublicAuthority.none,
    mutation: PublicMutation.read,
    features: ['publicListings'],
    relation: 'public_workspace_cards',
    select: ['workspace_id', 'name', 'document', 'updated_at'],
    order: ['workspace_id.asc'],
    pageSize: 1,
    timeoutSeconds: 12,
    output: 'PublicWorkspaceCard',
    cardinality: PublicCardinality.zeroOrOne,
  );

  /// The owner reads their workspace's public page, draft included.
  static const publicationPageRead = PublicOperationSpec(
    id: 'publication.page.read',
    surface: PublicSurface.management,
    principal: PublicPrincipal.authenticated,
    authority: PublicAuthority.owner,
    mutation: PublicMutation.read,
    features: [],
    rpc: 'my_workspace_public_page',
    params: {'p_workspace': 'uuid'},
    output: 'PublicationPage',
    cardinality: PublicCardinality.one,
  );

  /// The owner saves the public page and publishes or withdraws it; answers the public projection it produced.
  static const publicationPageSave = PublicOperationSpec(
    id: 'publication.page.save',
    surface: PublicSurface.management,
    principal: PublicPrincipal.authenticated,
    authority: PublicAuthority.owner,
    mutation: PublicMutation.write,
    features: ['publicListings'],
    rpc: 'save_workspace_public_page',
    params: {'p_workspace': 'uuid', 'p_document': 'jsonb', 'p_published': 'boolean'},
    input: {'p_document': 'PublicationInput'},
    output: 'PublicWorkspaceDocument',
    cardinality: PublicCardinality.one,
  );

  /// A signed-in account registers another installation's public endpoint in this directory, after an anonymous probe of that endpoint.
  static const directorySourcesRegister = PublicOperationSpec(
    id: 'directory.sources.register',
    surface: PublicSurface.participant,
    principal: PublicPrincipal.authenticated,
    authority: PublicAuthority.self,
    mutation: PublicMutation.write,
    features: [],
    rpc: 'register_public_directory',
    params: {'p_origin': 'text', 'p_key': 'text'},
    cardinality: PublicCardinality.none,
  );

  /// A signed-in account asks to join a published workspace, through its own session on that workspace's installation; admission stays the ordinary approval flow.
  static const workspaceProfileRequest = PublicOperationSpec(
    id: 'workspace.profile.request',
    surface: PublicSurface.participant,
    principal: PublicPrincipal.authenticated,
    authority: PublicAuthority.self,
    mutation: PublicMutation.request,
    features: ['publicListings'],
    rpc: 'request_public_workspace_profile',
    params: {'p_workspace': 'uuid'},
    cardinality: PublicCardinality.none,
  );

}

/// The same operations by stable identifier.
const Map<String, PublicOperationSpec> publicNetworkOperations = {
  'directory.sources.list': PublicNetworkOperations.directorySourcesList,
  'directory.workspaces.search': PublicNetworkOperations.directoryWorkspacesSearch,
  'directory.workspaces.detail': PublicNetworkOperations.directoryWorkspacesDetail,
  'publication.page.read': PublicNetworkOperations.publicationPageRead,
  'publication.page.save': PublicNetworkOperations.publicationPageSave,
  'directory.sources.register': PublicNetworkOperations.directorySourcesRegister,
  'workspace.profile.request': PublicNetworkOperations.workspaceProfileRequest,
};
