// SPDX-License-Identifier: AGPL-3.0-or-later
//
// #1847 — one public network contract, three renderings: the EXTERNAL
// OpenAPI document (public + participant operations), the INTERNAL one
// (management), and the Dart adapter catalogue the app's repositories read
// their bindings and allow-lists from. `contracts/public_network/
// operations.json` is the only hand-written source. It shares its field
// primitives with the MCP contract (#1609) and nothing else: this is not
// the MCP management catalogue.
import 'dart:convert';

import 'package:crypto/crypto.dart';

import '../contract_common/primitives.dart';

const publicNetworkGeneratedPaths = (
  external: 'contracts/public_network/generated/external.openapi.json',
  internal: 'contracts/public_network/generated/internal.openapi.json',
  dart: 'lib/core/public_network/public_network_operations.dart',
  supportMatrix: 'contracts/public_network/generated/support-matrix.json',
);

const _header =
    'GENERATED by `dart run tool/build_public_network_contract.dart` '
    'from contracts/public_network/operations.json (#1847). Do not edit.';

List<Map<String, dynamic>> _ops(Map<String, dynamic> contract) => [
  for (final o in contract['operations'] as List)
    Map<String, dynamic>.from(o as Map),
];

Map<String, dynamic> _schemas(Map<String, dynamic> contract) =>
    Map<String, dynamic>.from(contract['schemas'] as Map);

/// The JSON Schema of one public field.
Map<String, Object?> publicFieldSchema(Map<String, dynamic> f) =>
    switch (f['type']) {
      'currency' => {'type': 'string', 'pattern': r'^[A-Z]{3}$'},
      'decimal' => {
        'type': 'string',
        'pattern': r'^-?\d+(\.\d+)?$',
        'x-minimum': f['min'],
        'x-maximum': f['max'],
      },
      'https_url' => {
        'type': 'string',
        'format': 'uri',
        'pattern': '^https://',
        'maxLength': f['maxLength'] ?? 4000,
      },
      'https_origin' => {
        'type': 'string',
        'format': 'uri',
        'pattern': r'^https://[^/]+$',
      },
      'object' => {r'$ref': '#/components/schemas/${f['schema']}'},
      'array' => {
        'type': 'array',
        'items': {r'$ref': '#/components/schemas/${f['items']}'},
        if (f['maxItems'] != null) 'maxItems': f['maxItems'],
      },
      'integer_list' => {
        'type': 'array',
        'items': {'type': 'integer'},
      },
      'string_list' => {
        'type': 'array',
        'items': {'type': 'string', 'maxLength': 200},
      },
      _ => fieldSchema(f),
    };

/// One component schema. Unknown keys are allowed on the wire (an additive
/// field is ignored by the adapter), so `additionalProperties` stays open
/// for outputs and closed for inputs.
Map<String, Object?> publicSchema(
  String name,
  Map<String, dynamic> s, {
  required bool input,
}) {
  final fields = Map<String, dynamic>.from(s['fields'] as Map);
  return {
    'description': s['description'],
    'type': 'object',
    'additionalProperties': !input,
    'required': [
      for (final e in fields.entries)
        if ((e.value as Map)['required'] == true) e.key,
    ],
    'properties': {
      for (final e in fields.entries)
        e.key: publicFieldSchema(Map<String, dynamic>.from(e.value as Map)),
      if (s['must_understand'] != null)
        s['must_understand']: {
          'type': 'array',
          'items': {'type': 'string'},
          'description': 'Terms the reader must understand; an unknown one refuses the record.',
        },
    },
    if (s['must_understand'] != null) 'x-must-understand': s['must_understand'],
  };
}

Set<String> _referenced(
  Map<String, dynamic> contract,
  Iterable<Map<String, dynamic>> ops,
) {
  final schemas = _schemas(contract);
  final out = <String>{};
  void visit(String name) {
    if (!out.add(name)) return;
    final fields = Map<String, dynamic>.from(
      (schemas[name] as Map)['fields'] as Map,
    );
    for (final f in fields.values) {
      final m = f as Map;
      if (m['schema'] != null) visit(m['schema'] as String);
      if (m['items'] != null) visit(m['items'] as String);
    }
  }

  for (final op in ops) {
    final output = (op['output'] as Map)['schema'];
    if (output != null) visit(output as String);
    for (final s in (op['input'] as Map? ?? const {}).values) {
      visit(s as String);
    }
  }
  return out;
}

const _sqlTypes = {
  'uuid': {'type': 'string', 'format': 'uuid'},
  'text': {'type': 'string'},
  'boolean': {'type': 'boolean'},
};

Map<String, Object?> _operationDoc(Map<String, dynamic> op) {
  final binding = Map<String, dynamic>.from(op['binding'] as Map);
  final output = Map<String, dynamic>.from(op['output'] as Map);
  final schema = output['schema'] == null
      ? null
      : {r'$ref': '#/components/schemas/${output['schema']}'};
  final responseSchema = switch (output['cardinality']) {
    'many' || 'zero_or_one' => {'type': 'array', 'items': schema},
    'one' => schema,
    _ => null,
  };
  return {
    'operationId': camelCase(op['id'] as String),
    'summary': op['summary'],
    'x-deskilo-operation': op['id'],
    'x-deskilo-surface': op['surface'],
    'x-deskilo-principal': op['principal'],
    if (op['authority'] != null) 'x-deskilo-authority': op['authority'],
    'x-deskilo-mutation': op['mutation'],
    if (op['features'] != null && (op['features'] as List).isNotEmpty)
      'x-deskilo-features': op['features'],
    if (op['pagination'] != null) 'x-deskilo-pagination': op['pagination'],
    if (op['limits'] != null) 'x-deskilo-limits': op['limits'],
    if (op['idempotency'] != null) 'x-deskilo-idempotency': op['idempotency'],
    if (op['side_effects'] != null)
      'x-deskilo-side-effects': op['side_effects'],
    'x-deskilo-cardinality': output['cardinality'],
    'security': [
      if (op['principal'] == 'anonymous')
        {'publishableKey': <String>[]}
      else
        {'sessionBearer': <String>[]},
    ],
    if (binding['kind'] == 'table')
      'parameters': [
        {
          'name': 'select',
          'in': 'query',
          'required': true,
          'schema': {'const': (binding['select'] as List).join(',')},
        },
        {
          'name': 'order',
          'in': 'query',
          'schema': {'const': (binding['order'] as List).join(',')},
        },
        for (final e in Map<String, dynamic>.from(
          binding['filters'] as Map? ?? const {},
        ).entries)
          {
            'name': e.key,
            'in': 'query',
            'description': e.value,
            'schema': {'type': 'string'},
          },
        {
          'name': 'offset',
          'in': 'query',
          'schema': {'type': 'integer', 'minimum': 0},
        },
        {
          'name': 'limit',
          'in': 'query',
          'schema': {
            'type': 'integer',
            'maximum': (op['pagination'] as Map)['page_size'],
          },
        },
      ],
    if (binding['kind'] == 'rpc')
      'requestBody': {
        'required': true,
        'content': {
          'application/json': {
            'schema': {
              'type': 'object',
              'additionalProperties': false,
              'required': (binding['params'] as Map).keys.toList(),
              'properties': {
                for (final e in Map<String, dynamic>.from(
                  binding['params'] as Map,
                ).entries)
                  e.key: (op['input'] as Map?)?[e.key] != null
                      ? {
                          r'$ref':
                              '#/components/schemas/${(op['input'] as Map)[e.key]}',
                        }
                      : {..._sqlTypes[e.value]!, 'x-sql-type': e.value},
              },
            },
          },
        },
      },
    'responses': {
      '200': {
        'description': output['cardinality'] == 'none'
            ? 'Done; no body'
            : 'The allow-listed answer',
        if (responseSchema != null)
          'content': {
            'application/json': {'schema': responseSchema},
          },
      },
      if (op['principal'] == 'anonymous')
        '401': {'description': 'No or an invalid publishable key'}
      else
        '401': {
          'description':
              'No session, or a session that may not do this (PostgREST 42501)',
        },
      '400': {
        'description': 'A refusal: PostgREST error body with the SQL message',
      },
    },
  };
}

Map<String, Object?> _document(
  Map<String, dynamic> contract,
  List<Map<String, dynamic>> ops, {
  required String title,
  required String description,
}) {
  final schemas = _schemas(contract);
  final paths = <String, Map<String, Object?>>{};
  for (final op in ops) {
    final b = Map<String, dynamic>.from(op['binding'] as Map);
    final path = b['kind'] == 'table'
        ? '/rest/v1/${b['relation']}'
        : '/rest/v1/rpc/${b['rpc']}';
    final method = (b['method'] as String).toLowerCase();
    final entry = paths.putIfAbsent(path, () => {});
    final doc = _operationDoc(op);
    final existing = entry[method] as Map<String, Object?>?;
    if (existing == null) {
      entry[method] = doc;
    } else {
      // Two catalogue operations on one PostgREST route (search and
      // detail read the same table with different filters): one OpenAPI
      // operation, each identity kept with its own filters, page and
      // cardinality under x-deskilo-variants.
      Map<String, Object?> variant(
        Map<String, Object?> d,
        Map<String, dynamic> o,
      ) => {
        'summary': d['summary'],
        'filters': (o['binding'] as Map)['filters'],
        'order': ((o['binding'] as Map)['order'] as List).join(','),
        'pagination': d['x-deskilo-pagination'],
        'cardinality': d['x-deskilo-cardinality'],
      };
      final variants = <String, Object?>{
        ...?(existing['x-deskilo-variants'] as Map<String, Object?>?),
        if (existing['x-deskilo-variants'] == null)
          existing['x-deskilo-operation'] as String: variant(
            existing,
            ops.firstWhere((o) => o['id'] == existing['x-deskilo-operation']),
          ),
        op['id'] as String: variant(doc, op),
      };
      final orders = {for (final v in variants.values) (v as Map)['order']}
          .toList();
      final params = [
        for (final p in existing['parameters'] as List)
          if ((p as Map)['name'] == 'order')
            {
              ...p,
              'schema': {'enum': orders},
            }
          else
            p,
        for (final p in doc['parameters'] as List)
          if (!(existing['parameters'] as List).any(
            (q) => (q as Map)['name'] == (p as Map)['name'],
          ))
            p,
      ];
      entry[method] = {
        ...existing,
        'operationId': camelCase(b['relation'] as String),
        'summary':
            'Read published workspace cards (${variants.keys.join(', ')})',
        'x-deskilo-operation': null,
        'x-deskilo-pagination': null,
        'x-deskilo-cardinality': null,
        'x-deskilo-variants': variants,
        'parameters': params,
      }..removeWhere((k, v) => v == null);
    }
  }
  final referenced = _referenced(contract, ops);
  final inputs = {
    for (final op in ops) ...(op['input'] as Map? ?? const {}).values,
  };
  return {
    'x-generated': _header,
    'openapi': '3.1.0',
    'info': {
      'title': title,
      'version': '${contract['version']}',
      'description': description,
    },
    'x-deskilo-protocol': {
      'name': contract['protocol'],
      'version': contract['version'],
    },
    'x-deskilo-semantics': contract['semantics'],
    'servers': [
      {
        'url': '{installation}',
        'variables': {
          'installation': {'default': 'https://your-project.supabase.co'},
        },
      },
    ],
    'paths': paths,
    'components': {
      'securitySchemes': {
        'publishableKey': {
          'type': 'apiKey',
          'in': 'header',
          'name': 'apikey',
          'description': 'The installation\'s publishable (anon) key. No session bearer accompanies a public request.',
        },
        'sessionBearer': {
          'type': 'http',
          'scheme': 'bearer',
          'bearerFormat': 'JWT',
          'description': 'A signed-in session on the TARGET installation. It names the account; SQL decides what it may do.',
        },
      },
      'schemas': {
        for (final name in schemas.keys)
          if (referenced.contains(name))
            name: publicSchema(
              name,
              Map<String, dynamic>.from(schemas[name] as Map),
              input: inputs.contains(name),
            ),
      },
    },
  };
}

String _dartList(Iterable<Object?> xs) =>
    '[${xs.map((x) => "'$x'").join(', ')}]';

String _dartField(Map<String, dynamic> f) {
  final type = switch (f['type'] as String) {
    'enum' => 'enum_',
    'https_url' => 'httpsUrl',
    'https_origin' => 'httpsOrigin',
    'integer_list' => 'integerList',
    'string_list' => 'stringList',
    final t => t,
  };
  final args = [
    'PublicFieldType.$type',
    if (f['required'] == true) 'required: true',
    if (f['maxLength'] != null) 'maxLength: ${f['maxLength']}',
    if (f['min'] != null) 'min: ${f['min']}',
    if (f['max'] != null) 'max: ${f['max']}',
    if (f['values'] != null) 'values: ${_dartList(f['values'] as List)}',
    if (f['schema'] != null) "schema: '${f['schema']}'",
    if (f['items'] != null) "schema: '${f['items']}'",
    if (f['maxItems'] != null) 'maxItems: ${f['maxItems']}',
  ];
  return 'PublicField(${args.join(', ')})';
}

String _renderDart(Map<String, dynamic> contract) {
  final ops = _ops(contract);
  final schemas = _schemas(contract);
  final out = StringBuffer()
    ..writeln('// SPDX-License-Identifier: AGPL-3.0-or-later')
    ..writeln('//')
    ..writeln('// $_header')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln("import 'public_network_spec.dart';")
    ..writeln()
    ..writeln(
      '/// The public network protocol version these specs were generated from.',
    )
    ..writeln(
      'const int publicNetworkProtocolVersion = ${contract['version']};',
    )
    ..writeln()
    ..writeln('/// Every schema a record or an input is read with.')
    ..writeln('const Map<String, PublicSchema> publicNetworkSchemas = {');
  for (final e in schemas.entries) {
    final s = Map<String, dynamic>.from(e.value as Map);
    final fields = Map<String, dynamic>.from(s['fields'] as Map);
    out.writeln("  '${e.key}': PublicSchema(");
    out.writeln("    '${e.key}',");
    out.writeln('    {');
    for (final f in fields.entries) {
      out.writeln(
        "      '${f.key}': ${_dartField(Map<String, dynamic>.from(f.value as Map))},",
      );
    }
    out.writeln('    },');
    if (s['must_understand'] != null) {
      out.writeln("    mustUnderstand: '${s['must_understand']}',");
    }
    out.writeln('  ),');
  }
  out
    ..writeln('};')
    ..writeln()
    ..writeln(
      '/// Every catalogued operation, by a name its callers cannot misspell.',
    )
    ..writeln('abstract final class PublicNetworkOperations {');
  for (final op in ops) {
    final b = Map<String, dynamic>.from(op['binding'] as Map);
    final output = Map<String, dynamic>.from(op['output'] as Map);
    final pagination = op['pagination'] as Map?;
    final limits = op['limits'] as Map?;
    final cardinality = switch (output['cardinality']) {
      'zero_or_one' => 'zeroOrOne',
      final c => c,
    };
    out
      ..writeln('  /// ${op['summary']}')
      ..writeln(
        '  static const ${camelCase(op['id'] as String)} = PublicOperationSpec(',
      )
      ..writeln("    id: '${op['id']}',")
      ..writeln('    surface: PublicSurface.${op['surface']},')
      ..writeln('    principal: PublicPrincipal.${op['principal']},')
      ..writeln('    authority: PublicAuthority.${op['authority'] ?? 'none'},')
      ..writeln('    mutation: PublicMutation.${op['mutation']},')
      ..writeln('    features: ${_dartList(op['features'] as List)},');
    if (b['relation'] != null) out.writeln("    relation: '${b['relation']}',");
    if (b['rpc'] != null) out.writeln("    rpc: '${b['rpc']}',");
    if (b['select'] != null) {
      out.writeln('    select: ${_dartList(b['select'] as List)},');
    }
    if (b['order'] != null) {
      out.writeln('    order: ${_dartList(b['order'] as List)},');
    }
    if (pagination != null) {
      out.writeln('    pageSize: ${pagination['page_size']},');
    }
    if (limits?['timeout_seconds'] != null) {
      out.writeln('    timeoutSeconds: ${limits!['timeout_seconds']},');
    }
    if (b['params'] != null) {
      out.writeln(
        '    params: {${[for (final e in Map<String, dynamic>.from(b['params'] as Map).entries) "'${e.key}': '${e.value}'"].join(', ')}},',
      );
    }
    if (op['input'] != null) {
      out.writeln(
        '    input: {${[for (final e in Map<String, dynamic>.from(op['input'] as Map).entries) "'${e.key}': '${e.value}'"].join(', ')}},',
      );
    }
    if (output['schema'] != null) {
      out.writeln("    output: '${output['schema']}',");
    }
    out.writeln('    cardinality: PublicCardinality.$cardinality,');
    out.writeln(
      '    versions: [${(op['versions'] as List? ?? const []).join(', ')}],',
    );
    out.writeln(
      '    requires: ${_dartList(op['requires'] as List? ?? const [])},',
    );
    if (op['baseline'] == true) out.writeln('    baseline: true,');
    if (op['unlabelled'] != null) {
      out.writeln('    unlabelled: ${op['unlabelled']},');
    }
    if (op['revalidation'] == 'operation_header') {
      out.writeln('    revalidated: true,');
    }
    out
      ..writeln('  );')
      ..writeln();
  }
  out
    ..writeln('}')
    ..writeln()
    ..writeln('/// The same operations by stable identifier.')
    ..writeln(
      'const Map<String, PublicOperationSpec> publicNetworkOperations = {',
    );
  for (final op in ops) {
    out.writeln(
      "  '${op['id']}': PublicNetworkOperations.${camelCase(op['id'] as String)},",
    );
  }
  out
    ..writeln('};')
    ..writeln()
    ..writeln('/// #1847 B — the protocol versions this client speaks.')
    ..writeln(
      'const List<int> publicNetworkProtocolVersions = [${(contract['protocol_versions'] as List).join(', ')}];',
    )
    ..writeln()
    ..writeln('/// #1847 B — the capabilities this client understands.')
    ..writeln(
      'const Set<String> publicNetworkCapabilities = {${[for (final k in (contract['capabilities'] as Map).keys.toList()..sort()) "'$k'"].join(', ')}};',
    );
  return out.toString();
}

/// #1847 B — what an installation publishes about its external interface:
/// the protocol, its capabilities and every non-management operation with
/// the versions it accepts. No lifecycle (#1850 has not produced any), no
/// configuration, build, schema level or flag.
Map<String, Object?> publicNetworkDescriptor(Map<String, dynamic> contract) => {
  'protocol': contract['protocol'],
  'protocol_versions': contract['protocol_versions'],
  'capabilities': (contract['capabilities'] as Map).keys.toList()..sort(),
  'operations': [
    for (final op in _ops(contract))
      if (op['surface'] != 'management')
        {
          'id': op['id'],
          'versions': op['versions'],
          'requires': op['requires'],
          if (op['unlabelled'] != null) 'unlabelled': op['unlabelled'],
        },
  ],
};

/// The descriptor as the database answers it; the latest migration that
/// defines `public_network_descriptor()` carries this verbatim.
String renderPublicNetworkDescriptorSql(Map<String, dynamic> contract) =>
    '''create or replace function public.public_network_descriptor()
returns jsonb
language sql
immutable
set search_path = public
as \$descriptor\$
  select \$json\$${jsonEncode(publicNetworkDescriptor(contract))}\$json\$::jsonb
\$descriptor\$;''';

/// Every generated file, by path.
Map<String, String> renderPublicNetworkContract(Map<String, dynamic> contract) {
  final ops = _ops(contract);
  final external = [
    for (final op in ops)
      if (op['surface'] != 'management') op,
  ];
  final internal = [
    for (final op in ops)
      if (op['surface'] == 'management') op,
  ];
  return {
    publicNetworkGeneratedPaths.external: prettyJson(
      _document(
        contract,
        external,
        title: 'Deskilo public network — external interface',
        description:
            'What another installation, or an anonymous visitor, may '
            'call: anonymous discovery of deliberately published workspace '
            'cards, and an account\'s own participant requests on the target '
            'installation. Management of the publication is NOT part of this '
            'document. SQL grants, RLS and the RPC bodies remain the authority; '
            'this document grants nothing.',
      ),
    ),
    publicNetworkGeneratedPaths.internal: prettyJson(
      _document(
        contract,
        internal,
        title: 'Deskilo public network — internal management',
        description:
            'How a workspace owner authors what the external interface '
            'shows. Native owner sessions only; never anonymous, never an '
            'external integration surface.',
      ),
    ),
    publicNetworkGeneratedPaths.dart: _renderDart(contract),
  };
}

String _sha256(String text) => sha256.convert(utf8.encode(text)).toString();

/// #1847 B — the machine-readable support matrix: the hand-written
/// [support] input, the protocol and per-operation versions from the
/// catalogue, and the sha256 of every source, generated artifact and
/// evidence file it names ([read] returns a file's text). A changed test or
/// fixture changes its hash, so the matrix is regenerated with it.
String renderSupportMatrix(
  Map<String, dynamic> contract,
  Map<String, dynamic> support,
  String Function(String path) read,
) {
  final evidence = <String>{
    for (final key in ['server_profiles', 'client_profiles', 'pairs'])
      for (final row in support[key] as List)
        ...((row as Map)['evidence'] as List).cast<String>(),
  }.toList()..sort();
  return prettyJson({
    'x-generated': _header,
    'protocol': {
      'name': contract['protocol'],
      'versions': contract['protocol_versions'],
      'capabilities': (contract['capabilities'] as Map).keys.toList()..sort(),
    },
    'operations': {
      for (final op in _ops(contract))
        op['id']: {
          'surface': op['surface'],
          'versions': op['versions'],
          'requires': op['requires'],
          'baseline': op['baseline'] == true,
          if (op['unlabelled'] != null) 'unlabelled': op['unlabelled'],
        },
    },
    'axes': support['axes'],
    'server_profiles': support['server_profiles'],
    'client_profiles': support['client_profiles'],
    'platforms': support['platforms'],
    'pairs': support['pairs'],
    'hashes': {
      'sources': {
        for (final p in [
          'contracts/public_network/operations.json',
          'contracts/public_network/support.json',
        ])
          p: _sha256(read(p)),
      },
      'artifacts': {
        publicNetworkGeneratedPaths.dart: _sha256(_renderDart(contract)),
        'public_network_descriptor()': _sha256(
          renderPublicNetworkDescriptorSql(contract),
        ),
      },
      'evidence': {for (final p in evidence) p: _sha256(read(p))},
    },
  });
}
