// SPDX-License-Identifier: AGPL-3.0-or-later
//
// #1386 — `assets/help/` is generated from `docs/wiki/` and committed,
// and until this test nothing compared the two.
//
// The repository already treats the OTHER generated tree as a hard rule:
// `quality.yml` re-runs `build_arb` + `gen-l10n` and fails the build on
// any diff (HARD RULE #4). `build_help` had no equivalent, so the two
// generated trees sat in the same position with only one of them
// guarded, and a guide edited without a regeneration shipped in-app help
// that contradicted its own source.
//
// Measured on master at 042c2d14, a clean checkout plus one
// `dart run tool/build_help.dart`:
//
//     assets/help/de.md            -## Umsatzsteuer   +## MwSt.
//     assets/help/de.anchors.json  -"config.vat.overview": "Umsatzsteuer"
//                                  +"config.vat.overview": "MwSt."
//
// `Admin-Configuration-Guide.de.md:52` had read `## MwSt.` since it
// merged. German in-app help rendered a heading its source had renamed,
// and `config.vat.overview` — the help symbol that opens that very
// paragraph — resolved to the old wording.
//
// Three lines. The size is not the point: nothing would have said so.
//
// Why the existing help tests all pass on a stale file:
//
//   help_guide_parity_test  ratchets the en->locale anchor GAP; an
//                           anchor's id is unchanged, only its title
//                           went stale.
//   help_screen_test        asserts each <locale>.md exists and its
//                           images resolve; a stale file does both.
//   help_hint_test          asserts each topic is a substring of a
//                           heading IN THE GENERATED FILE — it reads the
//                           stale file, so it agrees with itself.
//
// That last one is the sharp edge: a pin that validates generated output
// against itself is satisfied by any self-consistent drift.
//
// This is an equality, not a ratchet. There is no partial credit for
// generated output: either it is what the tool produces from the sources
// in this commit, or the commit is shipping something nobody wrote.
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import '../../tool/build_help.dart';

void main() {
  for (final locale in guides.keys) {
    test('assets/help/$locale is what build_help produces today', () {
      final rendered = renderLocale(locale);

      // Named separately so a failure says WHICH of the two drifted: the
      // prose and the anchor titles come from the same sources but land
      // in different files, and the .md is the one a reader sees while
      // the .anchors.json is the one a help symbol resolves through.
      final markdown = File('$outDir/$locale.md');
      final anchors = File('$outDir/$locale.anchors.json');
      for (final file in [markdown, anchors]) {
        expect(file.existsSync(), isTrue,
            reason: '${file.path} is generated by '
                '`dart run tool/build_help.dart` and committed');
      }

      expect(markdown.readAsStringSync(), rendered.markdown,
          reason: '${markdown.path} is not what docs/wiki produces.\n'
              'A guide was edited without regenerating the help. Run\n'
              '  dart run tool/build_help.dart\n'
              'and commit assets/help/ in the same change as the guide.');
      expect(anchors.readAsStringSync(), rendered.anchorsJson,
          reason: '${anchors.path} is not what docs/wiki produces.\n'
              'Every help symbol resolves its heading text through this '
              'file, so a stale entry sends HelpDot to a title the guide '
              'no longer uses. Run `dart run tool/build_help.dart`.');
    });
  }

  test('the tool still lists guides this test can render', () {
    // Without this, a refactor that emptied `guides` would make every
    // assertion above vacuous — zero locales, zero comparisons, green.
    expect(guides.keys, containsAll(['en', 'fr', 'de', 'es', 'it']));
    for (final locale in guides.keys) {
      expect(renderLocale(locale).present, isNotEmpty,
          reason: '$locale renders from no source file at all, so its '
              'comparison above proves nothing');
    }
  });
}
