// SPDX-License-Identifier: 0BSD
//
// #1259 — the in-app help must not lose a guide in silence.
//
// `tool/build_help.dart` lists four guides per locale and compiles the
// ones it finds. It filtered with `where((f) => f.existsSync())` and
// only complained when the list came out EMPTY, so eight listed-but-
// absent files — the admin guides in fr, de, es and it — were dropped
// without a word. The tool printed `2 guide(s)` instead of `4` and
// exited 0, every time, for as long as they have been missing.
//
// The consequence is not a partial translation. An operator running a
// French space opens in-app help and finds NO operator content: no VAT
// chapter, no number sequences, no validation rules, no deployments.
// `help_screen_test` did not catch it because it asserts that each
// `<locale>.md` exists and that its image references resolve — never
// that the locales carry the same topics.
//
// Measured on master, 2026-09-16: en 176 anchors, fr/de/es/it 141 each.
// The 35 missing are exactly the anchors of the two English admin
// guides (16 `admin.*` + 19 `config.*`), the same 35 in all four.
//
// So this is a RATCHET, not an equality. The translations do not exist
// yet; a test demanding parity today could not be merged, and one that
// only ran after they landed would be a test nobody wrote. The gap is
// pinned at what it is, it may shrink, and it may never grow.
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

const _locales = ['fr', 'de', 'es', 'it'];

/// The anchors `build_help` generated for [locale].
Set<String> _anchors(String locale) {
  final file = File('assets/help/$locale.anchors.json');
  expect(file.existsSync(), isTrue,
      reason: 'assets/help/$locale.anchors.json is generated by '
          '`dart run tool/build_help.dart` and committed — regenerate it');
  return (jsonDecode(file.readAsStringSync()) as Map<String, dynamic>)
      .keys
      .toSet();
}

/// How many topics English has that [locale] does not.
///
/// 6→5 (2026-09-16): #1259 S2 — the Spanish configuration guide. The GAP
/// budget below STAYS 35: it is per locale, and Italian still misses both
/// admin guides, so the worst case has not moved.
///
/// 7→6 (2026-09-16): #1259 S2 — the German configuration guide. The GAP
/// budget below STAYS 35: it is checked per locale, and es/it are still
/// missing both admin guides, so the worst case has not moved.
///
/// 8→7 (2026-09-16): #1259 S2 translated Admin-Configuration-Guide into
/// French, so one of the eight listed-but-absent guides now exists. The
/// GAP budget below stays 35: it is checked per locale and de/es/it are
/// untouched, so the worst case has not moved.
///
/// 35 on 2026-09-16 (#1259): the two admin guides, untranslated. Lower
/// it as translations land — a slice that translates the configuration
/// guide takes it to 16, and the technical guide takes it to 0, at which
/// point this becomes an equality and the ratchet is retired.
const _missingBudget = 35;

void main() {
  test('no locale carries a topic English does not', () {
    // This direction is already true, so it is asserted flat rather than
    // budgeted: an anchor that exists only in a translation is a topic
    // no English reader can reach and no HelpDot can name.
    final offenders = <String>[];
    for (final locale in _locales) {
      final extra = _anchors(locale).difference(_anchors('en')).toList()..sort();
      for (final anchor in extra) {
        offenders.add('$locale: $anchor');
      }
    }
    expect(offenders, isEmpty,
        reason: 'These anchors exist in a translated guide and not in the '
            'English one, so nothing can link to them:\n  '
            '${offenders.join('\n  ')}');
  });

  test('the gap between English and each translation only shrinks', () {
    final en = _anchors('en');
    for (final locale in _locales) {
      final missing = en.difference(_anchors(locale)).length;
      expect(missing, lessThanOrEqualTo(_missingBudget),
          reason: 'assets/help/$locale.md is missing $missing of English\'s '
              '${en.length} topics, and the budget is $_missingBudget.\n'
              'A guide listed in tool/build_help.dart went missing, or a '
              'new English chapter was written without its translations. '
              'Run `dart run tool/build_help.dart` and read what it says '
              'is "listed but absent".');
    }
  });

  test('every guide build_help lists is actually there, or is budgeted', () {
    // The tool names what it cannot find on stderr; this pins the count
    // so that a NEW absence fails even though the eight known ones do
    // not. Without it, adding a fifth guide per locale and forgetting
    // four of them would look exactly like today.
    final source = File('tool/build_help.dart').readAsStringSync();
    final listed = RegExp(r"'([A-Za-z0-9._-]+\.md)'")
        .allMatches(source)
        .map((m) => m.group(1)!)
        .toSet();
    expect(listed.length, greaterThanOrEqualTo(20),
        reason: 'the guide list parsed to ${listed.length} entries — the '
            'shape of build_help.dart changed and this test is now '
            'measuring its own parser');

    final absent = listed
        .where((name) => !File('docs/wiki/$name').existsSync())
        .toList()
      ..sort();
    expect(absent.length, lessThanOrEqualTo(5),
        reason: 'tool/build_help.dart lists ${absent.length} guides that do '
            'not exist in docs/wiki, and 5 are known (#1259, the admin '
            'guides in fr/de/es/it):\n  ${absent.join('\n  ')}');
    expect(absent.every((name) => name.startsWith('Admin-')), isTrue,
        reason: 'the known-absent guides are the admin translations; '
            'something else is missing now:\n  ${absent.join('\n  ')}');
  });
}
