// SPDX-License-Identifier: AGPL-3.0-or-later
//
// #1259 — the in-app help must not lose a guide in silence.
//
// `tool/build_help.dart` lists four guides per locale and compiles the
// ones it finds. It filtered with `where((f) => f.existsSync())` and
// only complained when the list came out EMPTY, so eight listed-but-
// absent files — the admin guides in fr, de, es and it — were dropped
// without a word. The tool printed `2 guide(s)` instead of `4` and
// exited 0, every time, for as long as they have been missing.
//
// The consequence is not a partial translation. An operator running a
// French space opens in-app help and finds NO operator content: no VAT
// chapter, no number sequences, no validation rules, no deployments.
// `help_screen_test` did not catch it because it asserts that each
// `<locale>.md` exists and that its image references resolve — never
// that the locales carry the same topics.
//
// Measured on master, 2026-09-16: en 176 anchors, fr/de/es/it 141 each.
// The 35 missing are exactly the anchors of the two English admin
// guides (16 `admin.*` + 19 `config.*`), the same 35 in all four.
//
// So this is a RATCHET, not an equality. The translations do not exist
// yet; a test demanding parity today could not be merged, and one that
// only ran after they landed would be a test nobody wrote. The gap is
// pinned at what it is, it may shrink, and it may never grow.
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

const _locales = ['fr', 'de', 'es', 'it'];

/// The anchors `build_help` generated for [locale].
Set<String> _anchors(String locale) {
  final file = File('assets/help/$locale.anchors.json');
  expect(file.existsSync(), isTrue,
      reason: 'assets/help/$locale.anchors.json is generated by '
          '`dart run tool/build_help.dart` and committed — regenerate it');
  return (jsonDecode(file.readAsStringSync()) as Map<String, dynamic>)
      .keys
      .toSet();
}

/// #1259 is finished, so this file no longer budgets anything.
///
/// It began as a ratchet because the translations did not exist: en had
/// 176 anchors and fr/de/es/it had 141 each, the 35 missing being
/// exactly the two English admin guides. A test demanding parity then
/// could not have been merged, so the gap was pinned and walked down —
/// 35 (both admin guides absent) -> 16 (the configuration guide landed
/// in all four) -> 0 (the technical guide landed in all four).
///
/// At zero it becomes an EQUALITY, which is what the ratchet was for.
/// A budget of 0 and an equality are not the same thing to read: one
/// says "we are still working on it", the other says "a locale missing
/// a topic is a defect". All five now compile 4 guides and 177
/// anchors, so the second is the true statement.


void main() {
  test('no locale carries a topic English does not', () {
    // This direction is already true, so it is asserted flat rather than
    // budgeted: an anchor that exists only in a translation is a topic
    // no English reader can reach and no HelpDot can name.
    final offenders = <String>[];
    for (final locale in _locales) {
      final extra = _anchors(locale).difference(_anchors('en')).toList()..sort();
      for (final anchor in extra) {
        offenders.add('$locale: $anchor');
      }
    }
    expect(offenders, isEmpty,
        reason: 'These anchors exist in a translated guide and not in the '
            'English one, so nothing can link to them:\n  '
            '${offenders.join('\n  ')}');
  });

  test('every translation carries every topic English does', () {
    final en = _anchors('en');
    final offenders = <String>[];
    for (final locale in _locales) {
      for (final anchor in (en.difference(_anchors(locale)).toList()..sort())) {
        offenders.add('$locale: $anchor');
      }
    }
    expect(offenders, isEmpty,
        reason: 'These topics exist in English and in no translation, so a '
            'help symbol naming one would open the top of the guide '
            'instead of the paragraph (help_anchor_test asserts a symbol '
            'may only point into a guide all five languages have):\n  '
            '${offenders.join('\n  ')}\n\n'
            'A guide listed in tool/build_help.dart went missing, or a new '
            'English chapter was written without its translations. Run '
            '`dart run tool/build_help.dart` and read what it says is '
            '"listed but absent".');
  });

  test('every guide build_help lists is actually there', () {
    // The tool names what it cannot find on stderr and exits 0 anyway.
    // Adding a fifth guide per locale and forgetting four of them would
    // otherwise look exactly like success.
    final source = File('tool/build_help.dart').readAsStringSync();
    final listed = RegExp(r"'([A-Za-z0-9._-]+\.md)'")
        .allMatches(source)
        .map((m) => m.group(1)!)
        .toSet();
    expect(listed.length, greaterThanOrEqualTo(20),
        reason: 'the guide list parsed to ${listed.length} entries — the '
            'shape of build_help.dart changed and this test is now '
            'measuring its own parser');

    final absent = listed
        .where((name) => !File('docs/wiki/$name').existsSync())
        .toList()
      ..sort();
    // #1259 closed the last of them, so this is an equality now: every
    // guide the tool lists exists. `build_help` drops a listed-but-absent
    // file with only a line on stderr and still exits 0, which is how
    // eight of them stayed missing without anyone noticing.
    expect(absent, isEmpty,
        reason: 'tool/build_help.dart lists ${absent.length} guide(s) that '
            'do not exist in docs/wiki. The tool drops them with a line on '
            'stderr and exits 0, so nothing else will tell you:\n  '
            '${absent.join('\n  ')}');
  });
}
