// SPDX-License-Identifier: 0BSD
//
// The setup questionnaire speaks the app's five languages (#1366).
//
// `web/setup.html` is the first thing a new owner reads, and until #1366
// it spoke only French: `<html lang="fr">`, a French-only copy of the
// feature catalogue, French validation messages and a French confirm()
// dialog. An owner in Munich met a page the app itself would never show.
//
// Now every word on the page comes from `web/setup_l10n.js`, generated by
// `tool/build_setup_l10n.dart` from two sources: the app's ARB catalogue
// for anything the app already names (features, permissions, validation
// domains, countries), and `web/setup_l10n/setup_<locale>.json` for the
// page's own prose. These tests keep it that way:
//
//  * the generated file is what the generator produces today (a committed
//    generated file with no drift gate drifts silently);
//  * every locale carries exactly the keys English does, none blank, with
//    the same placeholders;
//  * every WorkspaceFeature reads, in every locale, exactly what the app's
//    Features screen reads — the page keeps no sixth copy of the catalogue;
//  * every key the page asks for exists, and none is orphaned;
//  * no French literal is left in the page itself (a heuristic lint, with a
//    test proving it fires).
//
// The behaviour half — each locale renders, sets <html lang> and the title,
// shows no French outside French, and exports byte-identical XML — runs in
// tool/setup/step_harness.mjs, driven by setup_runs_test.dart.
import 'dart:convert';
import 'dart:io';

import 'package:deskilo/features/workspace/domain/workspace_feature.dart';
import 'package:deskilo/features/workspace/presentation/feature_copy.dart';
import 'package:deskilo/features/workspace/presentation/feature_names.dart';
import 'package:deskilo/l10n/app_localizations.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';

import '../../tool/build_setup_l10n.dart';

const _html = 'web/setup.html';
const _prefix = 'window.SETUP_L10N=';

/// The generated resource, decoded.
Map<String, dynamic> _decode(String js) {
  final start = js.indexOf(_prefix);
  final end = js.lastIndexOf(';');
  return jsonDecode(js.substring(start + _prefix.length, end))
      as Map<String, dynamic>;
}

Set<String> _placeholders(String value) => {
  for (final m in RegExp(r'\{(\w+)\}').allMatches(value)) m.group(1)!,
};

/// Characters French prose carries and the page's code never needs.
final _frenchLetters = RegExp('[àâçéèêëîïôûùœÀÂÇÉÈÊÎÔÛÙŒ«»’]');

/// Accent-free words the page used to show — the ones an accent check
/// alone would let back in.
final _frenchWords = RegExp(
  r'\b(Suivant|Terminer|Exporter|Charger|Effacer|Ajouter|Supprimer|'
  r'Corriger|Masqué|requis|Oui|Non|Aucun|Aucune|Fichier|Jours|Nom|Prix|'
  r'Ville|Rue|Pays|Devise|Langue|Membres?|Abonnement|Forfaits?|Palier|'
  r'Relances?|Enregistr\w*|Assistant de configuration|mode expert|'
  r'toutes les)\b',
);

/// Markup text a reader would see: anything left once tags are stripped.
final _visibleWord = RegExp(r'[A-Za-zÀ-ÿ]{3,}');

/// The line numbers (1-based, with the line) of French natural language in
/// [html] outside the l10n resource.
///
/// Heuristic, deliberately. In `<script>`, a code line (not a `//` comment)
/// is flagged for a French letter or a former French literal. In markup,
/// every line is checked the same way — attribute values included, since
/// an `onclick="confirm('…')"` is prose — and additionally any visible
/// text node is flagged, because the page's chrome is filled from
/// `data-t` keys and its markup should carry no words at all. `<style>`
/// is skipped, and so is the one block between `l10n-exempt-begin` and
/// `l10n-exempt-end` (language names, statutory VAT labels, XML fallbacks).
List<String> frenchLiterals(String html) {
  final findings = <String>[];
  var inScript = false;
  var inStyle = false;
  var exempt = false;
  final lines = html.split('\n');
  for (var i = 0; i < lines.length; i++) {
    final line = lines[i];
    final trimmed = line.trim();
    if (trimmed.contains('l10n-exempt-begin')) {
      exempt = true;
      continue;
    }
    if (trimmed.contains('l10n-exempt-end')) {
      exempt = false;
      continue;
    }
    if (exempt) continue;
    if (line.contains('<style')) inStyle = true;
    if (inStyle) {
      if (line.contains('</style>')) inStyle = false;
      continue;
    }
    // A `<script>` opening line may carry markup before it; a `<script
    // src=…></script>` pair opens nothing.
    final opensScript = RegExp(r'<script>').hasMatch(line);
    if (inScript || opensScript) {
      if (line.contains('</script>')) inScript = false;
      if (opensScript && !line.contains('</script>')) inScript = true;
      if (trimmed.startsWith('//')) continue;
      if (_frenchLetters.hasMatch(line) || _frenchWords.hasMatch(line)) {
        findings.add('${i + 1}: $trimmed');
      }
      continue;
    }
    final text = line.replaceAll(RegExp(r'<[^>]*>'), ' ');
    final words = _visibleWord
        .allMatches(text)
        .map((m) => m.group(0)!)
        .where((w) => w != 'DesKilo' && w != 'DOCTYPE' && w != 'html');
    if (_frenchLetters.hasMatch(line) ||
        _frenchWords.hasMatch(line) ||
        words.isNotEmpty) {
      findings.add('${i + 1}: $trimmed');
    }
  }
  return findings;
}

void main() {
  late String html;
  late Map<String, dynamic> resource;

  setUpAll(() {
    html = File(_html).readAsStringSync();
    resource = _decode(File(setupL10nOutput).readAsStringSync());
  });

  test('web/setup_l10n.js is what build_setup_l10n produces today', () {
    expect(
      File(setupL10nOutput).readAsStringSync(),
      buildSetupL10n(),
      reason:
          'the setup questionnaire\'s strings drifted from their sources '
          '(ARB or web/setup_l10n/*.json) — run '
          '`dart run tool/build_setup_l10n.dart` and commit the result',
    );
  });

  group('page strings', () {
    Map<String, dynamic> strings(String locale) =>
        jsonDecode(File(setupStringsPath(locale)).readAsStringSync())
            as Map<String, dynamic>;

    for (final locale in setupLocales) {
      test('$locale has exactly the English keys, none blank, same '
          'placeholders', () {
        final en = strings('en');
        final own = strings(locale);
        expect(
          own.keys.toSet().difference(en.keys.toSet()),
          isEmpty,
          reason: 'keys $locale has and en does not',
        );
        expect(
          en.keys.toSet().difference(own.keys.toSet()),
          isEmpty,
          reason: 'keys $locale is missing',
        );
        final blank = [
          for (final e in own.entries)
            if (e.value is! String || (e.value as String).trim().isEmpty) e.key,
        ];
        expect(blank, isEmpty, reason: 'blank values in $locale');
        final drifted = [
          for (final key in en.keys)
            if (!_setEquals(
              _placeholders(en[key] as String),
              _placeholders(own[key] as String),
            ))
              key,
        ];
        expect(
          drifted,
          isEmpty,
          reason:
              'placeholders differ from en in $locale — the page '
              'fills them by name',
        );
      });
    }

    test('every key the page asks for exists, and no key is orphaned', () {
      final en = strings('en');
      final asked = {
        for (final m in RegExp(r"\bT\('(\w+)'").allMatches(html)) m.group(1)!,
        for (final m in RegExp(r'data-th?="(\w+)"').allMatches(html))
          m.group(1)!,
      };
      expect(
        asked.difference(en.keys.toSet()),
        isEmpty,
        reason:
            'setup.html asks for keys web/setup_l10n/setup_en.json '
            'does not have — it would show the raw key',
      );
      final orphans = [
        for (final key in en.keys)
          if (!html.contains("'$key'") && !html.contains('"$key"')) key,
      ];
      expect(
        orphans,
        isEmpty,
        reason:
            'keys nothing in setup.html reads any more — delete them '
            'from all five JSON files',
      );
    });
  });

  group('catalogue', () {
    for (final locale in setupLocales) {
      test('every WorkspaceFeature reads in $locale exactly as the app '
          'names and describes it', () {
        final l10n = lookupAppLocalizations(Locale(locale));
        final features = resource[locale]['feature'] as Map<String, dynamic>;
        expect(
          features.keys.toSet(),
          WorkspaceFeature.values.map((f) => f.name).toSet(),
        );
        final wrong = <String>[];
        for (final f in WorkspaceFeature.values) {
          final row = features[f.name] as List<dynamic>;
          final name = featureName(l10n, f);
          final description = featureDescription(l10n, f);
          if (row[0] != name || row[1] != description) wrong.add(f.name);
          if (name.trim().isEmpty || description.trim().isEmpty) {
            wrong.add('${f.name} (blank)');
          }
        }
        expect(wrong, isEmpty);
      });
    }

    test('FEATURES rows carry no label — the name comes from the ARB', () {
      final start = html.indexOf('const FEATURES=[');
      final block = html.substring(start, html.indexOf('\n];', start));
      final rows = block.split('\n').skip(1).toList();
      final labelled = rows
          .where((r) => !RegExp(r"^ \['[A-Za-z]+',[01]\],$").hasMatch(r))
          .toList();
      expect(
        labelled,
        isEmpty,
        reason:
            'a FEATURES row is [key, defaultOn]; a label written '
            'here is a setup-only copy that drifts from the app',
      );
      expect(rows, hasLength(WorkspaceFeature.values.length));
    });
  });

  group('the page', () {
    test('loads the resource before its own script and hardcodes no '
        'language', () {
      final resourceTag = html.indexOf('<script src="setup_l10n.js"></script>');
      final inline = html.indexOf('<script>');
      expect(resourceTag, isNot(-1));
      expect(resourceTag, lessThan(inline));
      expect(html, isNot(contains('lang="fr"')));
      expect(
        RegExp('<title>DesKilo</title>').hasMatch(html),
        isTrue,
        reason: 'the title is set from the chosen locale at load',
      );
    });

    test('carries no French literal outside the l10n resource', () {
      expect(
        frenchLiterals(html),
        isEmpty,
        reason:
            'user-facing text belongs in web/setup_l10n/setup_*.json '
            '(or the app ARB), read through T(key)',
      );
    });

    test('the exempt block stays small', () {
      final start = html.indexOf('l10n-exempt-begin');
      final end = html.indexOf('l10n-exempt-end');
      expect('l10n-exempt-begin'.allMatches(html), hasLength(1));
      expect(
        html.substring(start, end).split('\n').length,
        lessThanOrEqualTo(26),
        reason:
            'the exemption is for language names, statutory VAT '
            'labels and XML fallbacks — not a place to park prose',
      );
    });

    test('the French-literal lint fires on what it must catch', () {
      const page = '''
<!DOCTYPE html>
<html lang="en">
<body>
<p>Tout afficher sur une page</p>
<button onclick="if(confirm('Effacer toutes les réponses ?')){}"></button>
<span data-t="setupReset"></span>
<script src="setup_l10n.js"></script>
<script>
const a='Suivant';
// Un commentaire en français n'est pas affiché.
h('p',{},"Réglages de l'espace");
const b=T('setupNext');
// l10n-exempt-begin
const ENDONYMS={fr:'Français'};
// l10n-exempt-end
</script>
</body>
</html>''';
      final found = frenchLiterals(page).map((f) => f.split(':').first);
      expect(found, ['4', '5', '9', '11']);
    });
  });
}

bool _setEquals(Set<String> a, Set<String> b) =>
    a.length == b.length && a.containsAll(b);
