// SPDX-License-Identifier: AGPL-3.0-or-later
//
// #1609 — one operation contract, four renderings. `contracts/mcp/
// operations.json` is the only hand-written source; everything this
// returns is generated, committed, and compared by a drift test. The
// catalogue grants nothing: SQL stays the authority, and an operation
// appears as an MCP tool only once its handler exists (`handler: true`).
import 'dart:convert';

const generatedPaths = (
  tools: 'contracts/mcp/generated/tools.json',
  typescript: 'supabase/functions/_shared/mcp_contract.ts',
  dart: 'lib/core/mcp/mcp_operations.dart',
  openapi: 'contracts/mcp/generated/openapi.json',
);

const _header = 'GENERATED by `dart run tool/build_mcp_contract.dart` from '
    'contracts/mcp/operations.json (#1609). Do not edit.';

/// The JSON Schema of one typed field.
Map<String, Object?> fieldSchema(Map<String, dynamic> f) => switch (f['type']) {
      'uuid' => {'type': 'string', 'format': 'uuid'},
      'datetime' => {
          'type': 'string',
          'format': 'date-time',
          'pattern': r'(Z|[+-]\d{2}:\d{2})$',
        },
      'month' => {'type': 'string', 'pattern': r'^\d{4}-(0[1-9]|1[0-2])$'},
      'integer' => {
          'type': 'integer',
          if (f['min'] != null) 'minimum': f['min'],
          if (f['max'] != null) 'maximum': f['max'],
        },
      'boolean' => {'type': 'boolean'},
      'text' => {'type': 'string', 'maxLength': f['maxLength'] ?? 500},
      'enum' => {'type': 'string', 'enum': f['values']},
      final t => throw FormatException('unknown field type $t'),
    };

Map<String, Object?> inputSchema(Map<String, dynamic> op) {
  final input = Map<String, dynamic>.from(op['input'] as Map);
  return {
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      for (final e in input.entries)
        e.key: fieldSchema(Map<String, dynamic>.from(e.value as Map)),
    },
    'required': [
      for (final e in input.entries)
        if ((e.value as Map)['required'] == true) e.key,
    ],
  };
}

Map<String, Object?> envelopeSchema(Map<String, dynamic> contract) => {
      'type': 'object',
      'additionalProperties': false,
      'required': ['schema_version', 'request_id', 'operation', 'status'],
      'properties': {
        'schema_version': {'const': contract['version']},
        'request_id': {'type': 'string', 'format': 'uuid'},
        'operation': {
          'enum': [for (final o in contract['operations'] as List) (o as Map)['id']],
        },
        'workspace_id': {'type': 'string', 'format': 'uuid'},
        'status': {'enum': contract['statuses']},
        'data': {'type': 'object'},
        'event_id': {'type': 'string', 'format': 'uuid'},
        'error': {
          'type': 'object',
          'properties': {
            'code': {'type': 'string'},
            'fields': {'type': 'object', 'additionalProperties': {'type': 'string'}},
          },
        },
      },
    };

String _pretty(Object? o) => '${const JsonEncoder.withIndent('  ').convert(o)}\n';

String _camel(String snake) {
  final parts = snake.split('_');
  return parts.first +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
}

/// Every generated file, by path.
Map<String, String> renderMcpContract(Map<String, dynamic> contract) {
  final ops = [
    for (final o in contract['operations'] as List) Map<String, dynamic>.from(o as Map),
  ];
  final prefix = contract['tool_prefix'] as String;

  final tools = {
    'x-generated': _header,
    'version': contract['version'],
    'tools': [
      for (final op in ops)
        if (op['handler'] == true)
          {
            'name': '$prefix${op['id']}',
            'description': op['description'],
            'inputSchema': inputSchema(op),
            'annotations': {
              'readOnlyHint': op['mutation'] == 'read',
              'idempotentHint': op['idempotency'] == 'request_id',
            },
          },
    ],
  };

  final ts = StringBuffer()
    ..writeln('// SPDX-License-Identifier: AGPL-3.0-or-later')
    ..writeln('// $_header')
    ..writeln()
    ..writeln('export const MCP_CONTRACT_VERSION = ${contract['version']};')
    ..writeln('export const MCP_TOOL_PREFIX = "$prefix";')
    ..writeln('export type McpStatus =')
    ..writeln('${[for (final s in contract['statuses'] as List) '  | "$s"'].join('\n')};')
    ..writeln('export type McpOperationId =')
    ..writeln('${[for (final op in ops) '  | "${op['id']}"'].join('\n')};')
    ..writeln()
    ..writeln('export interface McpEnvelope<T = Record<string, unknown>> {')
    ..writeln('  schema_version: ${contract['version']};')
    ..writeln('  request_id: string;')
    ..writeln('  operation: McpOperationId;')
    ..writeln('  workspace_id?: string;')
    ..writeln('  status: McpStatus;')
    ..writeln('  data?: T;')
    ..writeln('  event_id?: string;')
    ..writeln('  error?: { code: string; fields?: Record<string, string> };')
    ..writeln('}')
    ..writeln()
    ..writeln('export interface McpOperation {')
    ..writeln('  id: McpOperationId;')
    ..writeln('  rpc: string | null;')
    ..writeln('  handler: boolean;')
    ..writeln('  authority: { kind: "self" | "member" | "permission"; permission?: string };')
    ..writeln('  features: string[];')
    ..writeln('  scope: "discovery" | "own" | "workspace";')
    ..writeln('  mutation: "read" | "write" | "request" | "decision";')
    ..writeln('  idempotency: "none" | "request_id";')
    ..writeln('  confirmation: "none" | "native";')
    ..writeln('  params: Record<string, string>;')
    ..writeln('  fixed: Record<string, unknown>;')
    ..writeln('  output: string[];')
    ..writeln('}')
    ..writeln()
    ..writeln('export const MCP_OPERATIONS: Record<McpOperationId, McpOperation> = {');
  for (final op in ops) {
    final input = Map<String, dynamic>.from(op['input'] as Map);
    final params = {
      for (final e in input.entries)
        if ((e.value as Map)['param'] != null) e.key: (e.value as Map)['param'],
    };
    ts.writeln('  ${op['id']}: ${jsonEncode({
      'id': op['id'],
      'rpc': op['rpc'],
      'handler': op['handler'] == true,
      'authority': op['authority'],
      'features': op['features'],
      'scope': op['scope'],
      'mutation': op['mutation'],
      'idempotency': op['idempotency'],
      'confirmation': op['confirmation'],
      'params': params,
      'fixed': op['fixed'] ?? const <String, Object?>{},
      'output': op['output'],
    })},');
  }
  ts
    ..writeln('};')
    ..writeln()
    ..writeln('export const MCP_INPUT_SCHEMAS: Record<McpOperationId, unknown> = {');
  for (final op in ops) {
    ts.writeln('  ${op['id']}: ${jsonEncode(inputSchema(op))},');
  }
  ts
    ..writeln('};')
    ..writeln()
    ..writeln('export const MCP_FORBIDDEN_INPUTS: readonly string[] = ${jsonEncode(contract['forbidden_inputs'])};');

  final dart = StringBuffer()
    ..writeln('// SPDX-License-Identifier: AGPL-3.0-or-later')
    ..writeln('//')
    ..writeln('// $_header')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln("import 'mcp_spec.dart';")
    ..writeln()
    ..writeln('/// The contract version these specs were generated from.')
    ..writeln('const int mcpContractVersion = ${contract['version']};')
    ..writeln()
    ..writeln('/// Names no input may carry: identity, role, SQL, targets, approval state.')
    ..writeln('const Set<String> mcpForbiddenInputs = {')
    ..writeln([for (final f in contract['forbidden_inputs'] as List) "  '$f',"].join('\n'))
    ..writeln('};')
    ..writeln()
    ..writeln('/// Every catalogued operation, handler or not.')
    ..writeln('const Map<String, McpOperationSpec> mcpOperations = {');
  for (final op in ops) {
    final input = Map<String, dynamic>.from(op['input'] as Map);
    final authority = Map<String, dynamic>.from(op['authority'] as Map);
    dart.writeln("  '${op['id']}': McpOperationSpec(");
    dart.writeln("    id: '${op['id']}',");
    dart.writeln('    rpc: ${op['rpc'] == null ? 'null' : "'${op['rpc']}'"},');
    dart.writeln('    handler: ${op['handler'] == true},');
    dart.writeln('    authority: McpAuthority.${authority['kind']},');
    dart.writeln('    permission: ${authority['permission'] == null ? 'null' : "'${authority['permission']}'"},');
    dart.writeln('    features: [${[for (final f in op['features'] as List) "'$f'"].join(', ')}],');
    dart.writeln('    scope: McpScope.${op['scope']},');
    dart.writeln('    mutation: McpMutation.${op['mutation']},');
    dart.writeln('    idempotent: ${op['idempotency'] == 'request_id'},');
    dart.writeln('    nativeConfirmation: ${op['confirmation'] == 'native'},');
    dart.writeln('    fields: {');
    for (final e in input.entries) {
      final f = Map<String, dynamic>.from(e.value as Map);
      final type = f['type'] == 'enum' ? 'enum_' : _camel(f['type'] as String);
      dart.writeln("      '${e.key}': McpField(McpFieldType.$type"
          "${f['required'] == true ? ', required: true' : ''}"
          "${f['min'] != null ? ', min: ${f['min']}' : ''}"
          "${f['max'] != null ? ', max: ${f['max']}' : ''}"
          "${f['maxLength'] != null ? ', maxLength: ${f['maxLength']}' : ''}"
          "${f['values'] != null ? ', values: [${[for (final v in f['values'] as List) "'$v'"].join(', ')}]' : ''}"
          "${f['param'] != null ? ", param: '${f['param']}'" : ''}),");
    }
    dart.writeln('    },');
    dart.writeln('    output: [${[for (final o in op['output'] as List) "'$o'"].join(', ')}],');
    dart.writeln('  ),');
  }
  dart.writeln('};');

  final openapi = {
    'x-generated': _header,
    'openapi': '3.1.0',
    'info': {
      'title': 'Deskilo MCP operation payloads',
      'version': '${contract['version']}',
      'description': 'Component schemas only. MCP is JSON-RPC over one HTTP '
          'endpoint; the real REST contract is the Supabase RPC path named '
          'by each operation (x-rpc). No route per tool exists.',
    },
    'paths': <String, Object?>{},
    'components': {
      'schemas': {
        'McpEnvelope': envelopeSchema(contract),
        for (final op in ops)
          '${_camel(op['id'] as String)[0].toUpperCase()}${_camel(op['id'] as String).substring(1)}Input': {
            ...inputSchema(op),
            'x-operation': op['id'],
            'x-rpc': op['rpc'],
            'x-handler': op['handler'] == true,
          },
      },
    },
  };

  return {
    generatedPaths.tools: _pretty(tools),
    generatedPaths.typescript: ts.toString(),
    generatedPaths.dart: dart.toString(),
    generatedPaths.openapi: _pretty(openapi),
  };
}
