#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# #1455 — the effective SQL contract, read from the replay, not from the
# migrations.
#
# Fifty-eight migrations patch stored function bodies by text anchor. A
# reviewer of the fifty-ninth cannot see the routine it produces, its
# overloads, or who may execute it, without replaying the whole history.
# So the database job writes that answer down after the replay:
#
#   assets/instance/contract.txt   one line per routine (identity
#                                  signature, kind, definer/invoker,
#                                  volatility, execute grants, a digest
#                                  of the effective body), per constraint
#                                  and per trigger — committed, and the
#                                  job fails when the replay disagrees,
#                                  exactly as the policy manifest does;
#   report/effective-schema.sql    the full effective definitions, as an
#                                  artifact of the run, for the reviewer
#                                  who wants to read a body rather than
#                                  trust a digest.
#
# A change made by an anchored patch moves the body digest of the routine
# it touched; a stale overload, a new grant, a changed constraint each
# appear as their own line. Unstable catalogue ids never enter the file.
set -uo pipefail

DB_URL=${1:?usage: contract_check.sh <db url>}
COMMITTED=assets/instance/contract.txt
mkdir -p report

fail() { echo "::error::$*"; exit 1; }

psql "$DB_URL" -v ON_ERROR_STOP=1 -At -c "
with r as (
  select 'routine ' || n.nspname || '.' || p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ') -> ' || pg_get_function_result(p.oid)
    || ' | ' || case p.prokind when 'f' then 'function' when 'p' then 'procedure' when 'a' then 'aggregate' else p.prokind::text end
    || ' | ' || case when p.prosecdef then 'definer' else 'invoker' end
    || ' | ' || case p.provolatile when 'i' then 'immutable' when 's' then 'stable' else 'volatile' end
    || ' | exec:' || coalesce(concat_ws(',',
         case when has_function_privilege('anon', p.oid, 'execute') then 'anon' end,
         case when has_function_privilege('authenticated', p.oid, 'execute') then 'authenticated' end,
         case when has_function_privilege('service_role', p.oid, 'execute') then 'service_role' end), '-')
    || ' | body:' || left(md5(pg_get_functiondef(p.oid)), 12) as line
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
), c as (
  select 'constraint ' || conrelid::regclass || '.' || conname || ' ' || pg_get_constraintdef(oid) as line
  from pg_constraint
  where connamespace = 'public'::regnamespace and contype in ('c', 'f', 'u', 'p', 'x')
), t as (
  select 'trigger ' || tgrelid::regclass || '.' || tgname || ' ' || pg_get_triggerdef(oid) as line
  from pg_trigger
  where not tgisinternal
    and tgrelid in (select oid from pg_class where relnamespace = 'public'::regnamespace)
)
select line from r union all select line from c union all select line from t order by 1" \
  > report/contract-lines.txt || fail "the contract query failed"

{
  echo '# GENERATED by `quality · database` (#1455): the effective SQL contract'
  echo '# of the public schema, read from the replay onto an empty Postgres.'
  echo '# One line per routine (identity signature, kind, definer/invoker,'
  echo '# volatility, execute grants, digest of the effective body), per'
  echo '# constraint and per trigger. A migration that patches a body by anchor'
  echo '# moves that routine'"'"'s digest here; a stale overload or a new grant is a'
  echo '# line of its own. The full definitions are the run'"'"'s'
  echo '# `effective-schema.sql` artifact.'
  echo '#'
  echo '# Update: run the database job; it writes this file and fails when it'
  echo '# differs. Copy the + side (keep this header).'
  cat report/contract-lines.txt
} > report/contract.txt

lines=$(grep -vc '^#' report/contract.txt)
[ "$lines" -gt 100 ] || fail "the contract has only $lines lines — the replay is not what it should be"
echo "contract: $lines lines (routines, constraints, triggers)"

# The readable half: every effective definition, for the reviewer.
C="$(docker ps --format '{{.Names}}' | grep -E '^supabase_db' | head -1)"
if [ -n "$C" ]; then
  docker exec "$C" pg_dump -U postgres -d postgres --schema-only --schema=public \
    --no-owner --no-privileges --no-comments 2>/dev/null \
    | grep -vE '^(--|SET |SELECT pg_catalog\.set_config|\\restrict|\\unrestrict|$)' \
    > report/effective-schema.sql || echo "::warning::effective-schema.sql could not be dumped"
  echo "effective-schema.sql: $(wc -l < report/effective-schema.sql | tr -d ' ') lines"
fi

if [ ! -s "$COMMITTED" ] || ! grep -qv '^#' "$COMMITTED"; then
  fail "$COMMITTED is empty — download this run's quality-database artifact and commit report/contract.txt as $COMMITTED"
fi

if ! diff -u <(grep -v '^#' "$COMMITTED") <(grep -v '^#' report/contract.txt); then
  fail "$COMMITTED is not what the migrations build — the diff above is the review; copy the + side into the file (keep its header)"
fi
echo "contract: committed file equals the replay"
