-- SPDX-License-Identifier: 0BSD
-- risk: transforming
--
-- 0227 (#1333, #1332) — the server decides whether a feature is on the way
-- the app does.
--
-- The client: a stored JSON boolean over the registry default, then every
-- `requires` parent on (`resolveEnabledFeatures` → `effectiveFeatures`). A
-- child stays stored `true` under a parent switched off — that is the
-- design (#800), so switching the parent back on restores it.
--
-- The server read the one flag in front of each gate, each with its own
-- default. Proven rolled back on the dev project before this file:
-- `{"moneyTab": false, "scheduledExpenses": true}` let
-- `create_expense_schedule` past its gate while the app showed the feature
-- off. The same held for price negotiations, invoice settlement, accessory
-- supplements and the admin invoicing grant in `has_permission_raw`.
--
-- ## One source, generated
--
-- `feature_registry()` is the Dart `featureManifest` — parent, default,
-- core — generated by `dart run tool/build_feature_registry_sql.dart` and
-- pinned by `test/lint/feature_registry_sql_test.dart`, which requires the
-- latest definition here to match the manifest byte for byte. Nobody types
-- a parent map twice.
--
-- * `feature_raw(flags, key)`        — a JSON boolean, or the default.
--                                     `"yes"`, `1`, `"true"` are not booleans.
-- * `feature_effective_in(flags, key)` — raw AND every parent raw.
-- * `feature_effective(ws, key)`     — the same, for a workspace row.
-- * `resolved_feature_flags(flags)`  — every registry key written out.
--
-- ## Every gate asks the helper
--
-- Twenty functions read `feature_flags`; every gate among them now calls
-- `feature_effective`. Each patch asserts its anchor — a silent no-op
-- here would leave a gate the old way while the lint said otherwise.
--
-- ## The import validates and completes the map
--
-- `import_workspace_configuration` replaced the map with whatever the file
-- held: no key pattern, no boolean check, and a partial map let 45
-- default-on platform features resolve ON in a workspace created with them
-- off (#1063). It now refuses what `set_feature_flags` refuses and writes
-- absent keys as a new workspace would (core → its default, platform →
-- off). The export writes every key resolved, so a dev → prod deployment
-- carries exactly the effective choice of the source and the completion
-- only ever applies to a hand-made or older file.
--
-- A stored child `true` under an off parent is NOT rewritten anywhere:
-- validity is a property of the effective set, never of the raw map (#800).

create or replace function public.feature_registry()
returns jsonb
language sql
immutable
set search_path = public
as $registry$
  select '{
    "calendarTab": {"parent": null, "default": true, "core": true},
    "eventsTab": {"parent": null, "default": true, "core": true},
    "moneyTab": {"parent": null, "default": true, "core": true},
    "services": {"parent": "moneyTab", "default": true, "core": true},
    "accessorySupplements": {"parent": "moneyTab", "default": false, "core": false},
    "onlinePayments": {"parent": "moneyTab", "default": false, "core": false},
    "invoicing": {"parent": "moneyTab", "default": true, "core": true},
    "adminInvoicing": {"parent": "invoicing", "default": false, "core": false},
    "pdfExport": {"parent": null, "default": true, "core": true},
    "seriesBooking": {"parent": null, "default": true, "core": true},
    "bookForOthers": {"parent": null, "default": true, "core": true},
    "pushNotifications": {"parent": null, "default": true, "core": true},
    "adminSeatBlocking": {"parent": null, "default": false, "core": false},
    "levelBooking": {"parent": null, "default": false, "core": false},
    "adminLevelAssign": {"parent": "levelBooking", "default": false, "core": false},
    "kioskMode": {"parent": null, "default": true, "core": false},
    "nfcBadges": {"parent": "kioskMode", "default": true, "core": false},
    "membersDirectory": {"parent": null, "default": true, "core": true},
    "whatsappIntegration": {"parent": "membersDirectory", "default": true, "core": false},
    "spaceQrCodes": {"parent": null, "default": true, "core": true},
    "coOwner": {"parent": null, "default": true, "core": false},
    "autoCheckInOut": {"parent": null, "default": false, "core": false},
    "dataExport": {"parent": null, "default": true, "core": true},
    "workingHours": {"parent": null, "default": true, "core": true},
    "invoicePdfTemplate": {"parent": "invoicing", "default": true, "core": false},
    "invoiceAddressWindow": {"parent": "invoicing", "default": true, "core": false},
    "memberNotifications": {"parent": null, "default": true, "core": true},
    "documents": {"parent": null, "default": true, "core": true},
    "dunning": {"parent": "invoicing", "default": true, "core": false},
    "memberReports": {"parent": "moneyTab", "default": true, "core": false},
    "deletionRequests": {"parent": null, "default": true, "core": true},
    "roleManagement": {"parent": null, "default": true, "core": true},
    "vatManagement": {"parent": "invoicing", "default": true, "core": false},
    "vatDeclarations": {"parent": "vatManagement", "default": true, "core": false},
    "einvoiceCustomerDelivery": {"parent": "invoicing", "default": true, "core": false},
    "planObjectDelete": {"parent": null, "default": true, "core": true},
    "notificationGrouping": {"parent": "eventsTab", "default": true, "core": true},
    "bookingPolicies": {"parent": null, "default": true, "core": true},
    "bookingGate": {"parent": "bookingPolicies", "default": true, "core": true},
    "nfcSeatTags": {"parent": null, "default": true, "core": false},
    "qrBadges": {"parent": "kioskMode", "default": true, "core": false},
    "kioskMemberPhotos": {"parent": "kioskMode", "default": true, "core": false},
    "subscriptionInvoices": {"parent": "invoicing", "default": true, "core": false},
    "usageInvoices": {"parent": "invoicing", "default": true, "core": false},
    "invoiceSettlement": {"parent": "invoicing", "default": true, "core": false},
    "invoiceJourney": {"parent": "invoicing", "default": true, "core": false},
    "messageGestures": {"parent": null, "default": true, "core": true},
    "uniqueMonograms": {"parent": null, "default": true, "core": true},
    "planMemberPhotos": {"parent": null, "default": true, "core": false},
    "regionalFormats": {"parent": null, "default": true, "core": true},
    "calendarHub": {"parent": null, "default": true, "core": true},
    "calendarViews": {"parent": "calendarHub", "default": true, "core": true},
    "messagesHub": {"parent": null, "default": true, "core": true},
    "reportDesigner": {"parent": "invoicePdfTemplate", "default": true, "core": false},
    "memberPage": {"parent": "membersDirectory", "default": true, "core": true},
    "invoicingWizard": {"parent": "invoicing", "default": true, "core": false},
    "expenseRepartition": {"parent": "invoicing", "default": true, "core": false},
    "settlementFold": {"parent": "invoiceSettlement", "default": true, "core": false},
    "configurationTransfer": {"parent": "dataExport", "default": true, "core": false},
    "navigationStyle": {"parent": null, "default": true, "core": true},
    "demoMode": {"parent": null, "default": true, "core": false},
    "instanceWizard": {"parent": null, "default": true, "core": false},
    "dataAccessLog": {"parent": "moneyTab", "default": true, "core": false},
    "memberDataExport": {"parent": null, "default": true, "core": true},
    "financeFaces": {"parent": "moneyTab", "default": true, "core": true},
    "paymentReminders": {"parent": "dunning", "default": true, "core": false},
    "supplyExpenses": {"parent": "services", "default": true, "core": false},
    "validationScopes": {"parent": null, "default": true, "core": false},
    "validationChain": {"parent": null, "default": true, "core": false},
    "richMessageRefs": {"parent": "memberNotifications", "default": true, "core": true},
    "calendarValidations": {"parent": "calendarHub", "default": true, "core": false},
    "usageRecords": {"parent": "invoicing", "default": true, "core": false},
    "reportDesignExchange": {"parent": "reportDesigner", "default": true, "core": false},
    "reportLayouts": {"parent": "reportDesigner", "default": true, "core": false},
    "personalInfo": {"parent": null, "default": true, "core": true},
    "managedProfiles": {"parent": "membersDirectory", "default": true, "core": false},
    "numberSequences": {"parent": "invoicing", "default": false, "core": false},
    "workspaceStatus": {"parent": "invoicing", "default": false, "core": false},
    "expenseRepartitionWizard": {"parent": "expenseRepartition", "default": false, "core": false},
    "multiSite": {"parent": null, "default": false, "core": false},
    "siteDocuments": {"parent": "multiSite", "default": false, "core": false},
    "vatGroups": {"parent": "vatManagement", "default": false, "core": false},
    "vatRateHistory": {"parent": "vatManagement", "default": false, "core": false},
    "vatCounterparty": {"parent": "vatManagement", "default": false, "core": false},
    "environmentPairs": {"parent": null, "default": true, "core": false},
    "deployments": {"parent": "environmentPairs", "default": true, "core": false},
    "managedProfileAccess": {"parent": "managedProfiles", "default": false, "core": false},
    "seatDayTimeline": {"parent": null, "default": true, "core": true},
    "memberPaymentTerms": {"parent": "invoicing", "default": true, "core": false},
    "usageReport": {"parent": "usageRecords", "default": true, "core": false},
    "reportTexts": {"parent": "reportDesigner", "default": true, "core": false},
    "letterStandard": {"parent": "reportLayouts", "default": true, "core": false},
    "vatReport": {"parent": "vatDeclarations", "default": true, "core": false},
    "priceNegotiations": {"parent": "moneyTab", "default": true, "core": false},
    "scheduledExpenses": {"parent": "moneyTab", "default": true, "core": false},
    "badgeSignIn": {"parent": "nfcBadges", "default": false, "core": false},
    "formHelpHints": {"parent": null, "default": true, "core": true},
    "uiAnimations": {"parent": null, "default": true, "core": true},
    "memberOrigin": {"parent": "membersDirectory", "default": false, "core": false},
    "memberEnvironments": {"parent": "environmentPairs", "default": false, "core": false},
    "workspaceLibrary": {"parent": null, "default": false, "core": false},
    "singleRoomLevelNames": {"parent": null, "default": true, "core": true},
    "publicHolidays": {"parent": null, "default": false, "core": false},
    "workspaceVocabulary": {"parent": null, "default": false, "core": false}
  }'::jsonb
$registry$;

revoke execute on function public.feature_registry() from public, anon;
grant execute on function public.feature_registry() to authenticated;

create or replace function public.feature_raw(p_flags jsonb, p_key text)
returns boolean
language sql
immutable
set search_path = public
as $$
  select case
    when jsonb_typeof(coalesce(p_flags, '{}'::jsonb) -> p_key) = 'boolean'
      then (p_flags -> p_key)::boolean
    else coalesce((public.feature_registry() -> p_key ->> 'default')::boolean, false)
  end;
$$;

revoke execute on function public.feature_raw(jsonb, text) from public, anon;
grant execute on function public.feature_raw(jsonb, text) to authenticated;

create or replace function public.feature_effective_in(p_flags jsonb, p_key text)
returns boolean
language plpgsql
immutable
set search_path = public
as $$
declare
  v_registry jsonb := public.feature_registry();
  v_key text := p_key;
  v_depth int := 0;
begin
  -- An unknown key is off: a gate must never open on a typo.
  if not v_registry ? p_key then
    return false;
  end if;
  while v_key is not null loop
    if not public.feature_raw(p_flags, v_key) then
      return false;
    end if;
    v_key := v_registry -> v_key ->> 'parent';
    v_depth := v_depth + 1;
    if v_depth > 32 then
      raise exception 'feature registry cycle at %', p_key;
    end if;
  end loop;
  return true;
end;
$$;

revoke execute on function public.feature_effective_in(jsonb, text) from public, anon;
grant execute on function public.feature_effective_in(jsonb, text) to authenticated;

create or replace function public.feature_effective(p_workspace_id uuid, p_key text)
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select coalesce(
    (select public.feature_effective_in(w.feature_flags, p_key)
       from public.workspaces w where w.id = p_workspace_id),
    false);
$$;

revoke execute on function public.feature_effective(uuid, text) from public, anon;
grant execute on function public.feature_effective(uuid, text) to authenticated;

create or replace function public.resolved_feature_flags(p_flags jsonb)
returns jsonb
language sql
immutable
set search_path = public
as $$
  select coalesce(jsonb_object_agg(k, public.feature_raw(p_flags, k)), '{}'::jsonb)
         || coalesce((select jsonb_object_agg(e.key, e.value)
                        from jsonb_each(coalesce(p_flags, '{}'::jsonb)) e
                       where not public.feature_registry() ? e.key
                         and jsonb_typeof(e.value) = 'boolean'), '{}'::jsonb)
    from jsonb_object_keys(public.feature_registry()) k;
$$;

revoke execute on function public.resolved_feature_flags(jsonb) from public, anon;
grant execute on function public.resolved_feature_flags(jsonb) to authenticated;

-- What an imported map becomes: the checks set_feature_flags makes, then
-- every registry key the file does not carry written as a NEW workspace
-- would have it — core at its default, platform off.
create or replace function public.imported_feature_flags(p_flags jsonb)
returns jsonb
language plpgsql
immutable
set search_path = public
as $$
declare
  v_registry jsonb := public.feature_registry();
  v_out jsonb := '{}'::jsonb;
  v_key text;
  v_value jsonb;
begin
  if p_flags is null or jsonb_typeof(p_flags) <> 'object' then
    raise exception 'feature flags must be an object';
  end if;
  for v_key, v_value in select * from jsonb_each(p_flags) loop
    if v_key !~ '^[A-Za-z][A-Za-z0-9]{0,63}$' then
      raise exception 'invalid feature key %', v_key;
    end if;
    if jsonb_typeof(v_value) <> 'boolean' then
      raise exception 'feature % must be true or false', v_key;
    end if;
    v_out := v_out || jsonb_build_object(v_key, v_value);
  end loop;
  for v_key in select jsonb_object_keys(v_registry) loop
    if not v_out ? v_key then
      v_out := v_out || jsonb_build_object(v_key,
        coalesce((v_registry -> v_key ->> 'core')::boolean, false)
          and coalesce((v_registry -> v_key ->> 'default')::boolean, false));
    end if;
  end loop;
  return v_out;
end;
$$;

revoke execute on function public.imported_feature_flags(jsonb) from public, anon;
grant execute on function public.imported_feature_flags(jsonb) to authenticated;

do $patch$
declare
  v_def text;
  v_old text;
  v_new text;
begin
  -- admin_create_reservation_for
  v_def := pg_get_functiondef('public.admin_create_reservation_for(uuid, uuid, uuid, timestamp with time zone, timestamp with time zone, uuid)'::regprocedure);
  v_old := $anchor$       and not coalesce(
      (select w.feature_flags -> 'adminLevelAssign' = to_jsonb(true)
         from public.workspaces w where w.id = p_workspace_id), false) then$anchor$;
  v_new := $anchor$       and not public.feature_effective(p_workspace_id, 'adminLevelAssign') then$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the admin_create_reservation_for anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- badge_auth_verify
  v_def := pg_get_functiondef('public.badge_auth_verify(text, text)'::regprocedure);
  v_old := $anchor$  select coalesce(w.feature_flags -> 'badgeSignIn' = to_jsonb(true), false)
     and coalesce(w.feature_flags -> 'nfcBadges' = to_jsonb(true), true)
     and coalesce(w.feature_flags -> 'kioskMode' = to_jsonb(true), true)$anchor$;
  v_new := $anchor$  select public.feature_effective_in(w.feature_flags, 'badgeSignIn')$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the badge_auth_verify anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- check_in_reservation
  v_def := pg_get_functiondef('public.check_in_reservation(uuid)'::regprocedure);
  v_old := $anchor$      and coalesce((
        select w.feature_flags->'bookForOthers' is distinct from 'false'::jsonb
        from public.workspaces w where w.id = v_res.workspace_id
      ), true)$anchor$;
  v_new := $anchor$      and public.feature_effective(v_res.workspace_id, 'bookForOthers')$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the check_in_reservation anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- create_expense_schedule
  v_def := pg_get_functiondef('public.create_expense_schedule(uuid, text, integer, date, text, integer, integer, date, text)'::regprocedure);
  v_old := $anchor$  if not coalesce((select w.feature_flags ->> 'scheduledExpenses'
                     from public.workspaces w where w.id = p_workspace_id)::boolean, true) then$anchor$;
  v_new := $anchor$  if not public.feature_effective(p_workspace_id, 'scheduledExpenses') then$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the create_expense_schedule anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- delete_plan_object
  v_def := pg_get_functiondef('public.delete_plan_object(text, uuid)'::regprocedure);
  v_old := $anchor$  select coalesce(w.feature_flags -> 'planObjectDelete' <> to_jsonb(false), true)
    into v_enabled from public.workspaces w where w.id = v_workspace_id;$anchor$;
  v_new := $anchor$  v_enabled := public.feature_effective(v_workspace_id, 'planObjectDelete');$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the delete_plan_object anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- level_booking_enabled
  v_def := pg_get_functiondef('public.level_booking_enabled(uuid)'::regprocedure);
  v_old := $anchor$  select coalesce(w.feature_flags -> 'levelBooking' = to_jsonb(true), false)
    from public.workspaces w where w.id = p_workspace_id;$anchor$;
  v_new := $anchor$  select public.feature_effective(p_workspace_id, 'levelBooking');$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the level_booking_enabled anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- member_statement
  v_def := pg_get_functiondef('public.member_statement(uuid, text)'::regprocedure);
  v_old := $anchor$         coalesce(feature_flags -> 'accessorySupplements' = to_jsonb(true), false),$anchor$;
  v_new := $anchor$         public.feature_effective_in(feature_flags, 'accessorySupplements'),$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the member_statement anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- propose_price_negotiation
  v_def := pg_get_functiondef('public.propose_price_negotiation(uuid, integer, integer, numeric, text, date, integer, jsonb)'::regprocedure);
  v_old := $anchor$  if not coalesce((select w.feature_flags ->> 'priceNegotiations' from public.workspaces w where w.id = v_member.workspace_id)::boolean, true) then$anchor$;
  v_new := $anchor$  if not public.feature_effective(v_member.workspace_id, 'priceNegotiations') then$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the propose_price_negotiation anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- set_seat_block
  v_def := pg_get_functiondef('public.set_seat_block(uuid, timestamp with time zone, timestamp with time zone)'::regprocedure);
  v_old := $anchor$      and coalesce((
        select w.feature_flags->'adminSeatBlocking' = 'true'::jsonb
        from public.workspaces w where w.id = v_workspace_id
      ), false)$anchor$;
  v_new := $anchor$      and public.feature_effective(v_workspace_id, 'adminSeatBlocking')$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the set_seat_block anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- settle_invoices
  v_def := pg_get_functiondef('public.settle_invoices(uuid, uuid, uuid[], text)'::regprocedure);
  v_old := $anchor$  if not coalesce((v_workspace.feature_flags ->> 'invoiceSettlement')::boolean, true) then$anchor$;
  v_new := $anchor$  if not public.feature_effective_in(v_workspace.feature_flags, 'invoiceSettlement') then$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the settle_invoices anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- stamp_accessory_supplements_since
  v_def := pg_get_functiondef('public.stamp_accessory_supplements_since()'::regprocedure);
  v_old := $anchor$  v_old boolean := coalesce(
    old.feature_flags -> 'accessorySupplements' = to_jsonb(true), false);
  v_new boolean := coalesce(
    new.feature_flags -> 'accessorySupplements' = to_jsonb(true), false);$anchor$;
  v_new := $anchor$  v_old boolean := public.feature_effective_in(old.feature_flags, 'accessorySupplements');
  v_new boolean := public.feature_effective_in(new.feature_flags, 'accessorySupplements');$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the stamp_accessory_supplements_since anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- sweep_billing_invoices
  v_def := pg_get_functiondef('public.sweep_billing_invoices(uuid)'::regprocedure);
  v_old := $anchor$       and coalesce((w.feature_flags ->> 'moneyTab')::boolean, true)
       and coalesce((w.feature_flags ->> 'invoicing')::boolean, true)$anchor$;
  v_new := $anchor$       and public.feature_effective_in(w.feature_flags, 'invoicing')$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the sweep_billing_invoices anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- sweep_billing_invoices
  v_def := pg_get_functiondef('public.sweep_billing_invoices(uuid)'::regprocedure);
  v_old := $anchor$and coalesce((v_flags ->> 'subscriptionInvoices')::boolean, true)$anchor$;
  v_new := $anchor$and public.feature_effective_in(v_flags, 'subscriptionInvoices')$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the sweep_billing_invoices anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- sweep_billing_invoices
  v_def := pg_get_functiondef('public.sweep_billing_invoices(uuid)'::regprocedure);
  v_old := $anchor$and coalesce((v_flags ->> 'usageInvoices')::boolean, true)$anchor$;
  v_new := $anchor$and public.feature_effective_in(v_flags, 'usageInvoices')$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the sweep_billing_invoices anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- sweep_day_end
  v_def := pg_get_functiondef('public.sweep_day_end(uuid)'::regprocedure);
  v_old := $anchor$  if not coalesce((
    select w.feature_flags->'autoCheckInOut' = 'true'::jsonb
    from public.workspaces w where w.id = p_workspace_id
  ), false) then$anchor$;
  v_new := $anchor$  if not public.feature_effective(p_workspace_id, 'autoCheckInOut') then$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the sweep_day_end anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- sweep_expense_schedules
  v_def := pg_get_functiondef('public.sweep_expense_schedules(uuid)'::regprocedure);
  v_old := $anchor$       and coalesce((w.feature_flags ->> 'moneyTab')::boolean, true)
       and coalesce((w.feature_flags ->> 'scheduledExpenses')::boolean, true)$anchor$;
  v_new := $anchor$       and public.feature_effective_in(w.feature_flags, 'scheduledExpenses')$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the sweep_expense_schedules anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- sweep_payment_reminders
  v_def := pg_get_functiondef('public.sweep_payment_reminders(uuid)'::regprocedure);
  v_old := $anchor$       and coalesce((w.feature_flags ->> 'dunning')::boolean, true)
       and coalesce((w.feature_flags ->> 'invoicing')::boolean, true)
       and coalesce((w.feature_flags ->> 'moneyTab')::boolean, true)
       and coalesce((w.feature_flags ->> 'paymentReminders')::boolean, true)$anchor$;
  v_new := $anchor$       and public.feature_effective_in(w.feature_flags, 'paymentReminders')$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the sweep_payment_reminders anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- has_permission_raw
  v_def := pg_get_functiondef('public.has_permission_raw(uuid, text)'::regprocedure);
  v_old := $anchor$or (perm = 'issueInvoices' and coalesce(w.feature_flags -> 'adminInvoicing' = to_jsonb(true), false))$anchor$;
  v_new := $anchor$or (perm = 'issueInvoices' and public.feature_effective_in(w.feature_flags, 'adminInvoicing'))$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the has_permission_raw anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- import_workspace_configuration
  v_def := pg_get_functiondef('public.import_workspace_configuration(uuid, jsonb, text)'::regprocedure);
  v_old := $anchor$feature_flags = case when v_ws ? 'feature_flags' then v_ws->'feature_flags' else w.feature_flags end$anchor$;
  v_new := $anchor$feature_flags = case when v_ws ? 'feature_flags' then public.imported_feature_flags(v_ws->'feature_flags') else w.feature_flags end$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the import_workspace_configuration anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

  -- export_workspace_configuration
  v_def := pg_get_functiondef('public.export_workspace_configuration(uuid)'::regprocedure);
  v_old := $anchor$'feature_flags', coalesce(w.feature_flags, '{}'::jsonb),$anchor$;
  v_new := $anchor$'feature_flags', public.resolved_feature_flags(w.feature_flags),$anchor$;
  if position(v_old in v_def) = 0 then
    raise exception '0227: the export_workspace_configuration anchor did not match';
  end if;
  execute replace(v_def, v_old, v_new);

end
$patch$;

-- Every gate now asks the helper: none may still read a flag by hand.
do $verify$
declare
  v_left text;
begin
  select string_agg(p.proname, ', ') into v_left
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.prokind = 'f'
     and p.proname not in ('create_workspace', 'set_feature_flags', 'deployable_entities',
                           'export_workspace_configuration', 'import_workspace_configuration',
                           'resolved_feature_flags', 'imported_feature_flags',
                           'feature_effective')
     and pg_get_functiondef(p.oid) ~ $re$feature_flags\s*->>?\s*'$re$;
  if v_left is not null then
    raise exception '0227: gates still reading a flag by hand: %', v_left;
  end if;
end
$verify$;

select public.set_deskilo_schema_version(227);
