// GENERATED by tool/capability_evidence.dart from docs/product/capabilities.json. Do not edit.
export const CAPABILITY_MANIFEST = "2026-10-10.1";
export const CAPABILITIES = [
  {
    "id": "booking",
    "status": "shipped",
    "evidence": [
      "unit:gated",
      "local_integration:gated"
    ]
  },
  {
    "id": "membership.allowances",
    "status": "shipped",
    "evidence": [
      "unit:gated",
      "local_integration:gated"
    ]
  },
  {
    "id": "statements.shared_expenses",
    "status": "shipped",
    "evidence": [
      "unit:gated",
      "local_integration:gated"
    ]
  },
  {
    "id": "approvals",
    "status": "shipped",
    "evidence": [
      "unit:gated",
      "local_integration:gated"
    ]
  },
  {
    "id": "payments.stripe",
    "status": "shipped",
    "evidence": [
      "unit:gated",
      "local_integration:gated"
    ]
  },
  {
    "id": "payments.paypal",
    "status": "shipped",
    "evidence": [
      "unit:gated"
    ]
  },
  {
    "id": "payments.mollie",
    "status": "shipped",
    "evidence": [
      "unit:gated",
      "local_integration:gated"
    ]
  },
  {
    "id": "payments.wero",
    "status": "shipped",
    "evidence": [
      "unit:gated"
    ]
  },
  {
    "id": "accounting.export",
    "status": "shipped",
    "evidence": [
      "unit:gated"
    ]
  },
  {
    "id": "einvoice.generate",
    "status": "shipped",
    "evidence": [
      "unit:gated"
    ]
  },
  {
    "id": "einvoice.transmit",
    "status": "shipped",
    "evidence": [
      "unit:gated"
    ]
  },
  {
    "id": "recovery.database_restore",
    "status": "shipped",
    "evidence": [
      "local_integration:gated"
    ]
  },
  {
    "id": "recovery.storage_auth",
    "status": "roadmap",
    "evidence": []
  },
  {
    "id": "demo",
    "status": "shipped",
    "evidence": [
      "unit:gated"
    ]
  },
  {
    "id": "mcp.read",
    "status": "shipped",
    "evidence": [
      "unit:gated",
      "local_integration:gated"
    ]
  },
  {
    "id": "mcp.write",
    "status": "shipped",
    "evidence": [
      "unit:gated",
      "local_integration:gated"
    ]
  },
  {
    "id": "mcp.consent",
    "status": "shipped",
    "evidence": [
      "unit:gated",
      "local_integration:gated"
    ]
  },
  {
    "id": "calendar.interchange",
    "status": "roadmap",
    "evidence": []
  }
];
