// SPDX-License-Identifier: 0BSD
// GENERATED by tool/build_setup_l10n.dart from workspaceProcesses (#1330).
// Do not edit: change lib/features/workspace/domain/workspace_process.dart and run `dart run tool/build_setup_l10n.dart`.
window.SETUP_PROCESSES=[
 {
  "key": "workspaceAccess",
  "subprocesses": [
   {
    "key": "people",
    "features": [
     "membersDirectory",
     "coOwner",
     "roleManagement",
     "personalInfo",
     "managedProfiles",
     "managedProfileAccess",
     "memberPage",
     "memberOrigin",
     "memberEnvironments"
    ]
   },
   {
    "key": "physicalAccess",
    "features": [
     "kioskMode",
     "nfcBadges",
     "nfcSeatTags",
     "qrBadges",
     "kioskMemberPhotos",
     "badgeSignIn",
     "spaceQrCodes"
    ]
   }
  ]
 },
 {
  "key": "spaceManagement",
  "subprocesses": [
   {
    "key": "structure",
    "features": [
     "multiSite",
     "planObjectDelete",
     "adminSeatBlocking"
    ]
   },
   {
    "key": "availability",
    "features": [
     "workingHours",
     "publicHolidays"
    ]
   },
   {
    "key": "presentation",
    "features": [
     "planMemberPhotos",
     "uniqueMonograms",
     "singleRoomLevelNames",
     "workspaceVocabulary"
    ]
   }
  ]
 },
 {
  "key": "reservationsUsage",
  "subprocesses": [
   {
    "key": "reservations",
    "features": [
     "seriesBooking",
     "bookForOthers",
     "levelBooking",
     "adminLevelAssign",
     "bookingPolicies",
     "bookingGate",
     "seatDayTimeline"
    ]
   },
   {
    "key": "attendance",
    "features": [
     "autoCheckInOut",
     "usageRecords"
    ]
   }
  ]
 },
 {
  "key": "coordination",
  "subprocesses": [
   {
    "key": "calendar",
    "features": [
     "calendarTab",
     "calendarHub",
     "calendarViews",
     "calendarValidations"
    ]
   },
   {
    "key": "decisions",
    "features": [
     "eventsTab",
     "validationScopes",
     "validationChain",
     "deletionRequests"
    ]
   },
   {
    "key": "communication",
    "features": [
     "memberNotifications",
     "notificationGrouping",
     "richMessageRefs",
     "messageGestures",
     "messagesHub"
    ]
   }
  ]
 },
 {
  "key": "membershipCommerce",
  "subprocesses": [
   {
    "key": "pricing",
    "features": [
     "services",
     "accessorySupplements",
     "priceNegotiations",
     "memberPaymentTerms",
     "carnets"
    ]
   }
  ]
 },
 {
  "key": "billingPayments",
  "subprocesses": [
   {
    "key": "records",
    "features": [
     "moneyTab",
     "financeFaces",
     "memberReports"
    ]
   },
   {
    "key": "invoicing",
    "features": [
     "invoicing",
     "adminInvoicing",
     "subscriptionInvoices",
     "usageInvoices",
     "invoiceSettlement",
     "invoiceJourney",
     "invoicingWizard",
     "settlementFold",
     "numberSequences"
    ]
   },
   {
    "key": "collection",
    "features": [
     "onlinePayments",
     "dunning",
     "paymentReminders"
    ]
   },
   {
    "key": "expenses",
    "features": [
     "supplyExpenses",
     "expenseRepartitionWizard",
     "scheduledExpenses",
     "expenseRepartition"
    ]
   },
   {
    "key": "tax",
    "features": [
     "vatManagement",
     "vatDeclarations",
     "vatGroups",
     "vatRateHistory",
     "vatCounterparty"
    ]
   }
  ]
 },
 {
  "key": "documentsInformation",
  "subprocesses": [
   {
    "key": "documents",
    "features": [
     "documents",
     "pdfExport",
     "invoicePdfTemplate",
     "invoiceAddressWindow",
     "letterStandard"
    ]
   },
   {
    "key": "reportDesign",
    "features": [
     "reportDesignExchange",
     "reportLayouts",
     "reportTexts",
     "reportDesigner",
     "usageReport",
     "vatReport"
    ]
   },
   {
    "key": "privacy",
    "features": [
     "dataAccessLog",
     "memberDataExport",
     "dataExport"
    ]
   }
  ]
 },
 {
  "key": "operations",
  "subprocesses": [
   {
    "key": "configuration",
    "features": [
     "workspaceStatus",
     "environmentPairs",
     "deployments",
     "configurationTransfer",
     "workspaceLibrary",
     "instanceWizard"
    ]
   },
   {
    "key": "experience",
    "features": [
     "formHelpHints",
     "uiAnimations",
     "regionalFormats",
     "navigationStyle",
     "demoMode"
    ]
   }
  ]
 },
 {
  "key": "integrations",
  "subprocesses": [
   {
    "key": "delivery",
    "features": [
     "pushNotifications",
     "whatsappIntegration",
     "einvoiceCustomerDelivery"
    ]
   }
  ]
 }
];
